import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'pl' | 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Default context value to prevent undefined errors during hot reload
const defaultContextValue: LanguageContextType = {
  language: 'pl' as Language,
  setLanguage: () => {},
  t: (key: string) => key
};

const translations = {
  pl: {
    // Navigation
    'nav.home': 'Strona główna',
    'nav.admin': 'Panel CMS',
    'nav.myAccount': 'Moje konto',
    'nav.login': 'Zaloguj się',
    'nav.logout': 'Wyloguj się',
    
    // Auth
    'auth.signIn': 'Zaloguj się',
    'auth.email': 'Email',
    'auth.password': 'Hasło',
    'auth.confirmPassword': 'Potwierdź hasło',
    'auth.signUp': 'Zarejestruj się',
    'auth.signUpLink': 'Nie masz konta? Zarejestruj się',
    'auth.signInLink': 'Masz już konto? Zaloguj się',
    'auth.resetPassword': 'Resetuj hasło',
    'auth.resetPasswordLink': 'Zapomniałeś hasła?',
    
    // Font Editor
    'fonts.title': 'Czcionki',
    'fonts.editor': 'Edytor czcionek',
    'fonts.description': 'Zarządzaj typografią aplikacji',
    'fonts.selectGoogleFont': 'Wybierz czcionkę Google Fonts',
    'fonts.preview': 'Podgląd czcionki',
    'fonts.sampleHeading': 'Przykładowy nagłówek',
    'fonts.sampleText': 'To jest przykładowy tekst pokazujący jak wygląda wybrana czcionka w różnych rozmiarach. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'fonts.settings': 'Ustawienia czcionki',
    'fonts.headingSize': 'Rozmiar nagłówków',
    'fonts.bodySize': 'Rozmiar tekstu',
    'fonts.lineHeight': 'Wysokość linii',
    'fonts.fontWeight': 'Grubość czcionki',
    'fonts.apply': 'Zastosuj ustawienia',
    'fonts.reset': 'Przywróć domyślne',
    'fonts.activeFont': 'Aktywna czcionka',
    'fonts.family': 'Rodzina',
    'fonts.sizes': 'Rozmiary',
    'fonts.applied': 'Czcionka zastosowana',
    
    // Color Editor
    'colors.title': 'Kolory',
    'colors.editor': 'Edytor schematów kolorów',
    'colors.description': 'Personalizuj kolorystykę aplikacji',
    'colors.colorSchemeEditor': 'Edytor schematów kolorów',
    'colors.manageColors': 'Zarządzaj kolorystyką aplikacji',
    'colors.presetSchemes': 'Gotowe schematy kolorów',
    'colors.currentPreview': 'Podgląd bieżących kolorów',
    'colors.customScheme': 'Niestandardowy schemat kolorów',
    'colors.primary': 'Podstawowy',
    'colors.secondary': 'Pomocniczy',
    'colors.accent': 'Akcent',
    'colors.background': 'Tło',
    'colors.primaryHSL': 'Kolor podstawowy (HSL)',
    'colors.secondaryHSL': 'Kolor pomocniczy (HSL)',
    'colors.accentHSL': 'Kolor akcentu (HSL)',
    'colors.backgroundHSL': 'Kolor tła (HSL)',
    'colors.applyCustom': 'Zastosuj niestandardowy schemat',
    'colors.resetDefault': 'Przywróć domyślny schemat',
    'colors.applied': 'Schemat kolorów zastosowany',
    'colors.active': 'Aktywny',
    
    // Text Editor
    'textEditor.title': 'Edytor tekstu',
    'textEditor.advanced': 'Zaawansowany edytor do formatowania treści',
    'textEditor.format': 'Formatuj tekst z zaawansowanymi opcjami stylowania',
    'textEditor.content': 'Treść',
    'textEditor.placeholder': 'Używaj tego editora do formatowania zawartości...',
    'textEditor.preview': 'Podgląd',
    'textEditor.previewDesc': 'Używaj tego editora do formatowania zawartości...',
    'textEditor.font': 'Czcionka',
    'textEditor.fontSize': 'Rozmiar czcionki',
    'textEditor.fontWeight': 'Grubość czcionki',
    'textEditor.lineHeight': 'Wysokość linii',
    'textEditor.letterSpacing': 'Odstęp między literami',
    'textEditor.textColor': 'Kolor tekstu',
    'textEditor.backgroundColor': 'Kolor tła',
    'textEditor.textSaved': 'Tekst zapisany',
    'textEditor.changesSaved': 'Zmiany zostały zastosowane',
    'textEditor.textCopied': 'Tekst skopiowany',
    'textEditor.copiedToClipboard': 'Tekst został skopiowany do schowka',
    
    // CMS Common
    'cms.sectionManagement': 'Zarządzanie sekcjami',
    'cms.addSection': 'Dodaj sekcję',
    'cms.position': 'Pozycja',
    'cms.elements': 'Elementów',
    'cms.visibleToPartners': 'Widoczne dla partnerów',
    'cms.visibleToClients': 'Widoczne dla klientów', 
    'cms.visibleToEveryone': 'Widoczne dla wszystkich',
    'cms.visibleToSpecjalista': 'Widoczne dla specjalistów',
    'cms.edit': 'Edytuj',
    'cms.delete': 'Usuń',
    'cms.addItem': 'Dodaj element',
    'cms.active': 'Aktywny',
    
    // Account section
    'account.title': 'Konto',
    'account.description': 'Zarządzaj swoim kontem administratora',
    'account.profile': 'Profil',
    'account.email': 'Email:',
    'account.userRole': 'Rola użytkownika:',
    'account.administrator': 'Administrator',
    'account.password': 'Hasło',
    'account.currentPassword': 'Hasło (aktualne)',
    'account.newPassword': 'Hasło (nowe)',
    'account.confirmPassword': 'Potwierdź hasło',
    'account.changePassword': 'Zmień hasło',
    'account.currentPasswordPlaceholder': 'Wprowadź aktualne hasło',
    'account.newPasswordPlaceholder': 'Wprowadź nowe hasło',
    'account.confirmPasswordPlaceholder': 'Potwierdź nowe hasło',
    
    // Admin Panel
    'admin.title': 'Panel administracyjny',
    'admin.cmsManagement': 'Zarządzanie treścią',
    'admin.sections': 'Sekcje',
    'admin.pages': 'Strony',
    'admin.userManagement': 'Zarządzanie użytkownikami',
    'admin.addSection': 'Dodaj sekcję',
    'admin.addPage': 'Dodaj stronę',
    'admin.sectionTitle': 'Tytuł sekcji',
    'admin.pageTitle': 'Tytuł strony',
    'admin.slug': 'Slug',
    'admin.content': 'Treść',
    'admin.save': 'Zapisz',
    'admin.cancel': 'Anuluj',
    'admin.edit': 'Edytuj',
    'admin.delete': 'Usuń',
    'admin.active': 'Aktywny',
    'admin.inactive': 'Nieaktywny',
    'admin.visibleToPartners': 'Widoczne dla partnerów',
    'admin.visibleToClients': 'Widoczne dla klientów',
    'admin.visibleToEveryone': 'Widoczne dla wszystkich',
    'admin.visibleToSpecjalista': 'Widoczne dla specjalistów',
    'admin.published': 'Opublikowane',
    'admin.unpublished': 'Nieopublikowane',
    'admin.fonts': 'Czcionki',
    'admin.colors': 'Kolory',
    'admin.textEditor': 'Edytor tekstu',
    'admin.account': 'Konto',
    'admin.users': 'Użytkownicy',
    'admin.sectionManagement': 'Zarządzanie sekcjami',
    'admin.addItem': 'Dodaj element',
    'admin.moveUp': 'Przenieś w górę',
    'admin.moveDown': 'Przenieś w dół',
    'admin.itemType': 'Typ elementu',
    'admin.itemTitle': 'Tytuł elementu',
    'admin.description': 'Opis',
    'admin.url': 'URL',
    'admin.icon': 'Ikona',
    'admin.media': 'Media',
    'admin.altText': 'Tekst alternatywny',
    'admin.uploadMedia': 'Prześlij media',
    'admin.formatting': 'Formatowanie',
    'admin.textFormatting': 'Formatowanie tekstu',
    'admin.titleFormatting': 'Formatowanie tytułu',
    'admin.metaTitle': 'Meta tytuł',
    'admin.metaDescription': 'Meta opis',
    'admin.pagePosition': 'Pozycja strony',
    'admin.pageVisibility': 'Widoczność strony',
    'admin.userRole': 'Rola użytkownika',
    'admin.userEmail': 'Email użytkownika',
    'admin.userStatus': 'Status użytkownika',
    'admin.confirmationSent': 'Potwierdzenie wysłane',
    'admin.emailConfirmed': 'Email potwierdzony',
    'admin.created': 'Utworzono',
    'admin.updated': 'Zaktualizowano',
    'admin.exportUsers': 'Eksportuj użytkowników',
    'admin.inviteUser': 'Zaproś użytkownika',
    'admin.loadingUsers': 'Ładowanie użytkowników...',
    'admin.loadingPages': 'Ładowanie stron...',
    'admin.noUsers': 'Brak użytkowników',
    'admin.noPages': 'Brak stron',
    'admin.noSections': 'Brak sekcji',
    'admin.noItems': 'Brak elementów w tej sekcji',
    'admin.main': 'Główna',
    'admin.nestedSections': 'Sekcje zagnieżdżone',
    'admin.addElement': 'Dodaj element',
    'admin.addElementToSection': 'Dodaj element do sekcji',
    'admin.addElementWithCells': 'Dodaj element z komórkami',
    'admin.editSection': 'Edytuj sekcję',
    'admin.deleteSection': 'Usuń sekcję',
    'admin.editElement': 'Edytuj element',
    'admin.deleteElement': 'Usuń element',
    'admin.addNestedSection': 'Dodaj sekcję zagnieżdżoną',
    'admin.editNestedSection': 'Edytuj sekcję zagnieżdżoną',
    'admin.deleteNestedSection': 'Usuń sekcję zagnieżdżoną',
    'admin.addNewSection': 'Dodaj nową sekcję do strony',
    'admin.configureSection': 'Skonfiguruj wygląd i zawartość nowej sekcji',
    'admin.saveChanges': 'Zapisz zmiany',
    'admin.elementType': 'Typ elementu',
    'admin.elementTitle': 'Tytuł elementu',
    'admin.elementDescription': 'Opis Elementu',
    'admin.elementCreated': 'Element został pomyślnie dodany do sekcji',
    'admin.noElementsInSection': 'Brak elementów w tej sekcji',
    'admin.editPage': 'Edytuj stronę',
    'admin.editPageSection': 'Edytuj sekcję strony',
    'admin.editPageElement': 'Edytuj element strony',
    
    // Registration
    'auth.eqId': 'EQ ID',
    'auth.role': 'Wybierz rolę',
    'auth.roleClient': 'Klient',
    'auth.rolePartner': 'Partner', 
    'auth.roleSpecialist': 'Specjalista',
    'auth.selectRole': 'Wybierz swoją rolę',
    'auth.forgotPassword': 'Zapomniałem hasła',
    'auth.passwordResetSent': 'Link do resetowania hasła został wysłany',
    'auth.enterEmailForReset': 'Wprowadź adres email aby zresetować hasło',
    
    // Common
    'common.loading': 'Ładowanie...',
    'common.error': 'Błąd',
    'common.success': 'Sukces',
    'common.close': 'Zamknij',
    'common.share': 'Udostępnij',
    'common.noContent': 'Brak treści',
    'common.position': 'Pozycja',
    
    // Account
    'account.myAccount': 'Moje konto',
    'account.updateProfile': 'Aktualizuj profil',
    
    // Errors
    'error.notFound': 'Strona nie została znaleziona',
    'error.forbidden': 'Brak dostępu',
    'error.returnHome': 'Powrót do strony głównej',
    
    // Share
    'share.section': 'Udostępnij sekcję',
    'share.copied': 'Link skopiowany do schowka!',
    
    // Page errors
    'page.accessDenied': 'Brak dostępu do strony',
    'page.contactAdmin': 'Ta strona jest dostępna tylko dla użytkowników z odpowiednimi uprawnieniami. Skontaktuj się z administratorem aby uzyskać dostęp.',
    'page.noContent': 'Ta strona nie ma jeszcze zawartości',
    'page.contentSoon': 'Zawartość zostanie dodana wkrótce.',
    'page.back': 'Wstecz',
    
    // Messages
    'messages.accountBlocked': 'Konto zablokowane',
    'messages.accountDeactivated': 'Twoje konto zostało dezaktywowane przez administratora. Nie masz dostępu do funkcji aplikacji.',
    'messages.contactAdminError': 'Jeśli uważasz, że to pomyłka, skontaktuj się z administratorem systemu.',
    'messages.welcomeBack': 'Witaj w systemie Pure Life!',
    'messages.loginSuccess': 'Zalogowano pomyślnie',
    'messages.passwordChanged': 'Hasło zostało pomyślnie zmienione.',
    'messages.passwordError': 'Nie udało się zmienić hasła.',
    
    // Toast messages
    'toast.error': 'Błąd',
    'toast.success': 'Sukces', 
    'toast.info': 'Informacja',
    'toast.redirect': 'Przekierowanie',
    'toast.positionChanged': 'Pozycja zmieniona',
    'toast.pageCreated': 'Strona utworzona',
    'toast.visibilityUpdated': 'Widoczność zaktualizowana',
    'toast.pageUpdated': 'Strona zaktualizowana',
    'toast.pageDeleted': 'Strona usunięta',
    'toast.sectionAdded': 'Sekcja dodana',
    'toast.elementAdded': 'Element dodany',
    'toast.sectionUpdated': 'Sekcja zaktualizowana',
    'toast.elementUpdated': 'Element zaktualizowany',
    'toast.sectionDeleted': 'Sekcja usunięta',
    'toast.elementDeleted': 'Element usunięty',
    'toast.linkCopied': 'Link skopiowany',
    'toast.textFormatted': 'Tekst sformatowany',
    
    // Error messages
    'error.loadClients': 'Nie udało się załadować klientów.',
    'error.changeRole': 'Nie udało się zmienić roli klienta.',
    'error.confirmEmail': 'Nie udało się potwierdzić emaila klienta.',
    'error.changeStatus': 'Nie udało się zmienić statusu klienta.',
    'error.currentPassword': 'Podaj aktualne hasło.',
    'error.passwordMismatch': 'Hasła nie są identyczne.',
    'error.passwordLength': 'Hasło musi mieć co najmniej 6 znaków.',
    'error.incorrectPassword': 'Aktualne hasło jest nieprawidłowe.',
    'error.changePassword': 'Nie udało się zmienić hasła.',
    'error.fillAllFields': 'Wypełnij wszystkie pola.',
    'error.createClient': 'Nie udało się utworzyć klienta.',
    'error.loadCMS': 'Nie udało się załadować danych CMS.',
    'error.createSection': 'Nie udało się utworzyć sekcji.',
    'error.deleteSection': 'Nie udało się usunąć sekcji.',
    'error.changeSectionPosition': 'Nie udało się zmienić pozycji sekcji.',
    'error.updateSection': 'Nie udało się zaktualizować sekcji.',
    'error.addElement': 'Nie udało się dodać elementu.',
    'error.updateElement': 'Nie udało się zaktualizować elementu.',
    'error.deleteElement': 'Nie udało się usunąć elementu.',
    'error.loadPages': 'Nie udało się pobrać stron.',
    'error.createPage': 'Nie udało się utworzyć strony.',
    'error.updatePageVisibility': 'Nie udało się zaktualizować widoczności strony.',
    'error.updatePage': 'Nie udało się zaktualizować strony.',
    'error.deletePage': 'Nie udało się usunąć strony.',
    
    // Success messages  
    'success.roleChanged': 'Rola klienta została zmieniona.',
    'success.emailConfirmed': 'Email klienta został potwierdzony.',
    'success.emailAlreadyConfirmed': 'Email był już wcześniej potwierdzony.',
    'success.statusChanged': 'Status klienta został zmieniony.',
    'success.passwordChanged': 'Hasło zostało zmienione.',
    'success.clientCreated': 'Nowy klient został utworzony.',
    'success.redirectToAccount': 'Zostaniesz przekierowany na stronę Moje konto.',
    'success.sectionCreated': 'Nowa sekcja została utworzona.',
    'success.sectionDeleted': 'Sekcja została usunięta.',
    'success.sectionMovedUp': 'Sekcja została przesunięta w górę.',
    'success.sectionMovedDown': 'Sekcja została przesunięta w dół.',
    'success.sectionUpdated': 'Sekcja została zaktualizowana.',
    'success.elementAdded': 'Element został dodany.',
    'success.elementUpdated': 'Element został zaktualizowany.',
    'success.elementDeleted': 'Element został usunięty.',
    'success.pageCreated': 'Nowa strona została pomyślnie utworzona.',
    'success.pageVisibilityUpdated': 'Widoczność strony została zaktualizowana.',
    'success.pageUpdated': 'Strona została zaktualizowana.',
    'success.pageDeleted': 'Strona została usunięta.',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.admin': 'CMS-Panel',
    'nav.myAccount': 'Mein Konto',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',
    
    // Auth
    'auth.signIn': 'Anmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.signUp': 'Registrieren',
    'auth.signUpLink': 'Kein Konto? Registrieren',
    'auth.signInLink': 'Bereits ein Konto? Anmelden',
    'auth.resetPassword': 'Passwort zurücksetzen',
    'auth.resetPasswordLink': 'Passwort vergessen?',
    
    // Admin Panel
    'admin.title': 'Administrationsbereich',
    'admin.cmsManagement': 'Inhaltsverwaltung',
    'admin.sections': 'Bereiche',
    'admin.pages': 'Seiten',
    'admin.userManagement': 'Benutzerverwaltung',
    'admin.addSection': 'Bereich hinzufügen',
    'admin.addPage': 'Seite hinzufügen',
    'admin.sectionTitle': 'Bereichstitel',
    'admin.pageTitle': 'Seitentitel',
    'admin.slug': 'Slug',
    'admin.content': 'Inhalt',
    'admin.save': 'Speichern',
    'admin.cancel': 'Abbrechen',
    'admin.edit': 'Bearbeiten',
    'admin.delete': 'Löschen',
    'admin.active': 'Aktiv',
    'admin.inactive': 'Inaktiv',
    'admin.visibleToPartners': 'Sichtbar für Partner',
    'admin.visibleToClients': 'Sichtbar für Kunden',
    'admin.visibleToEveryone': 'Sichtbar für alle',
    'admin.visibleToSpecjalista': 'Sichtbar für Spezialisten',
    'admin.published': 'Veröffentlicht',
    'admin.unpublished': 'Unveröffentlicht',
    'admin.contentManagement': 'Inhaltsverwaltung',
    'admin.fonts': 'Schriftarten',
    'admin.colors': 'Farben',
    'admin.textEditor': 'Texteditor',
    'admin.account': 'Konto',
    'admin.users': 'Benutzer',
    'admin.sectionManagement': 'Bereichsverwaltung',
    'admin.addItem': 'Element hinzufügen',
    'admin.moveUp': 'Nach oben verschieben',
    'admin.moveDown': 'Nach unten verschieben',
    'admin.itemType': 'Elementtyp',
    'admin.itemTitle': 'Elementtitel',
    'admin.description': 'Beschreibung',
    'admin.url': 'URL',
    'admin.icon': 'Icon',
    'admin.media': 'Medien',
    'admin.altText': 'Alt-Text',
    'admin.uploadMedia': 'Medien hochladen',
    'admin.formatting': 'Formatierung',
    'admin.textFormatting': 'Textformatierung',
    'admin.titleFormatting': 'Titelformatierung',
    'admin.metaTitle': 'Meta-Titel',
    'admin.metaDescription': 'Meta-Beschreibung',
    'admin.pagePosition': 'Seitenposition',
    'admin.pageVisibility': 'Seitensichtbarkeit',
    'admin.userRole': 'Benutzerrolle',
    'admin.userEmail': 'Benutzer-E-Mail',
    'admin.userStatus': 'Benutzerstatus',
    'admin.confirmationSent': 'Bestätigung gesendet',
    'admin.emailConfirmed': 'E-Mail bestätigt',
    'admin.created': 'Erstellt',
    'admin.updated': 'Aktualisiert',
    'admin.exportUsers': 'Benutzer exportieren',
    'admin.inviteUser': 'Benutzer einladen',
    'admin.loadingUsers': 'Benutzer werden geladen...',
    'admin.loadingPages': 'Seiten werden geladen...',
    'admin.noUsers': 'Keine Benutzer',
    'admin.noPages': 'Keine Seiten',
    'admin.noSections': 'Keine Bereiche',
    'admin.noItems': 'Keine Elemente in diesem Bereich',
    'admin.main': 'Hauptseite',
    'admin.nestedSections': 'Verschachtelte Bereiche',
    'admin.addElement': 'Element hinzufügen',
    'admin.addElementToSection': 'Element zum Bereich hinzufügen',
    'admin.addElementWithCells': 'Element mit Zellen hinzufügen',
    'admin.editSection': 'Bereich bearbeiten',
    'admin.deleteSection': 'Bereich löschen',
    'admin.editElement': 'Element bearbeiten',
    'admin.deleteElement': 'Element löschen',
    'admin.addNestedSection': 'Verschachtelten Bereich hinzufügen',
    'admin.editNestedSection': 'Verschachtelten Bereich bearbeiten',
    'admin.deleteNestedSection': 'Verschachtelten Bereich löschen',
    'admin.addNewSection': 'Neuen Bereich zur Seite hinzufügen',
    'admin.configureSection': 'Aussehen und Inhalt des neuen Bereichs konfigurieren',
    'admin.saveChanges': 'Änderungen speichern',
    'admin.elementType': 'Elementtyp',
    'admin.elementTitle': 'Elementtitel',
    'admin.elementDescription': 'Elementbeschreibung',
    'admin.elementCreated': 'Element wurde erfolgreich zum Bereich hinzugefügt',
    'admin.noElementsInSection': 'Keine Elemente in diesem Bereich',
    'admin.editPage': 'Seite bearbeiten',
    'admin.editPageSection': 'Seitenbereich bearbeiten',
    'admin.editPageElement': 'Seitenelement bearbeiten',
    
    // Registration
    'auth.eqId': 'EQ ID',
    'auth.role': 'Rolle wählen',
    'auth.roleClient': 'Kunde',
    'auth.rolePartner': 'Partner',
    'auth.roleSpecialist': 'Spezialist',
    'auth.selectRole': 'Wählen Sie Ihre Rolle',
    'auth.forgotPassword': 'Passwort vergessen',
    'auth.passwordResetSent': 'Link zum Zurücksetzen des Passworts wurde gesendet',
    'auth.enterEmailForReset': 'E-Mail-Adresse eingeben, um Passwort zurückzusetzen',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.close': 'Schließen',
    'common.share': 'Teilen',
    'common.noContent': 'Kein Inhalt',
    'common.position': 'Position',
    
    // Account
    'account.myAccount': 'Mein Konto',
    'account.profile': 'Profil',
    'account.updateProfile': 'Profil aktualisieren',
    
    // Errors
    'error.notFound': 'Seite nicht gefunden',
    'error.forbidden': 'Kein Zugriff',
    'error.returnHome': 'Zurück zur Startseite',
    
    // Share
    'share.section': 'Bereich teilen',
    'share.copied': 'Link in die Zwischenablage kopiert!',
    
    // Page errors
    'page.accessDenied': 'Kein Zugriff auf die Seite',
    'page.contactAdmin': 'Diese Seite ist nur für Benutzer mit entsprechenden Berechtigungen verfügbar. Wenden Sie sich an den Administrator, um Zugriff zu erhalten.',
    'page.noContent': 'Diese Seite hat noch keinen Inhalt',
    'page.contentSoon': 'Inhalte werden bald hinzugefügt.',
    'page.back': 'Zurück',
    
    // Messages  
    'messages.accountBlocked': 'Konto gesperrt',
    'messages.accountDeactivated': 'Ihr Konto wurde vom Administrator deaktiviert. Sie haben keinen Zugriff auf die Anwendungsfunktionen.',
    'messages.contactAdminError': 'Wenn Sie glauben, dass dies ein Fehler ist, wenden Sie sich an den Systemadministrator.',
    'messages.welcomeBack': 'Willkommen im Pure Life System!',
    'messages.loginSuccess': 'Erfolgreich angemeldet',
    'messages.passwordChanged': 'Passwort erfolgreich geändert.',
    'messages.passwordError': 'Passwort konnte nicht geändert werden.',
    
    // Toast messages
    'toast.error': 'Fehler',
    'toast.success': 'Erfolg',
    'toast.info': 'Information', 
    'toast.redirect': 'Weiterleitung',
    'toast.positionChanged': 'Position geändert',
    'toast.pageCreated': 'Seite erstellt',
    'toast.visibilityUpdated': 'Sichtbarkeit aktualisiert',
    'toast.pageUpdated': 'Seite aktualisiert',
    'toast.pageDeleted': 'Seite gelöscht',
    'toast.sectionAdded': 'Bereich hinzugefügt',
    'toast.elementAdded': 'Element hinzugefügt',
    'toast.sectionUpdated': 'Bereich aktualisiert',
    'toast.elementUpdated': 'Element aktualisiert',
    'toast.sectionDeleted': 'Bereich gelöscht',
    'toast.elementDeleted': 'Element gelöscht',
    'toast.linkCopied': 'Link kopiert',
    'toast.textFormatted': 'Text formatiert',
    
    // Error messages
    'error.loadClients': 'Kunden konnten nicht geladen werden.',
    'error.changeRole': 'Kundenrolle konnte nicht geändert werden.',
    'error.confirmEmail': 'Kunden-E-Mail konnte nicht bestätigt werden.',
    'error.changeStatus': 'Kundenstatus konnte nicht geändert werden.',
    'error.currentPassword': 'Geben Sie das aktuelle Passwort ein.',
    'error.passwordMismatch': 'Passwörter stimmen nicht überein.',
    'error.passwordLength': 'Passwort muss mindestens 6 Zeichen haben.',
    'error.incorrectPassword': 'Aktuelles Passwort ist falsch.',
    'error.changePassword': 'Passwort konnte nicht geändert werden.',
    'error.fillAllFields': 'Füllen Sie alle Felder aus.',
    'error.createClient': 'Kunde konnte nicht erstellt werden.',
    'error.loadCMS': 'CMS-Daten konnten nicht geladen werden.',
    'error.createSection': 'Bereich konnte nicht erstellt werden.',
    'error.deleteSection': 'Bereich konnte nicht gelöscht werden.',
    'error.changeSectionPosition': 'Bereichsposition konnte nicht geändert werden.',
    'error.updateSection': 'Bereich konnte nicht aktualisiert werden.',
    'error.addElement': 'Element konnte nicht hinzugefügt werden.',
    'error.updateElement': 'Element konnte nicht aktualisiert werden.',
    'error.deleteElement': 'Element konnte nicht gelöscht werden.',
    'error.loadPages': 'Seiten konnten nicht abgerufen werden.',
    'error.createPage': 'Seite konnte nicht erstellt werden.',
    'error.updatePageVisibility': 'Seitensichtbarkeit konnte nicht aktualisiert werden.',
    'error.updatePage': 'Seite konnte nicht aktualisiert werden.',
    'error.deletePage': 'Seite konnte nicht gelöscht werden.',
    
    // Success messages
    'success.roleChanged': 'Kundenrolle wurde geändert.',
    'success.emailConfirmed': 'Kunden-E-Mail wurde bestätigt.',
    'success.emailAlreadyConfirmed': 'E-Mail war bereits bestätigt.',
    'success.statusChanged': 'Kundenstatus wurde geändert.',
    'success.passwordChanged': 'Passwort wurde geändert.',
    'success.clientCreated': 'Neuer Kunde wurde erstellt.',
    'success.redirectToAccount': 'Sie werden zur Kontoseite weitergeleitet.',
    'success.sectionCreated': 'Neuer Bereich wurde erstellt.',
    'success.sectionDeleted': 'Bereich wurde gelöscht.',
    'success.sectionMovedUp': 'Bereich wurde nach oben verschoben.',
    'success.sectionMovedDown': 'Bereich wurde nach unten verschoben.',
    'success.sectionUpdated': 'Bereich wurde aktualisiert.',
    'success.elementAdded': 'Element wurde hinzugefügt.',
    'success.elementUpdated': 'Element wurde aktualisiert.',
    'success.elementDeleted': 'Element wurde gelöscht.',
    'success.pageCreated': 'Neue Seite wurde erfolgreich erstellt.',
    'success.pageVisibilityUpdated': 'Seitensichtbarkeit wurde aktualisiert.',
    'success.pageUpdated': 'Seite wurde aktualisiert.',
    'success.pageDeleted': 'Seite wurde gelöscht.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.admin': 'CMS Panel',
    'nav.myAccount': 'My Account',
    'nav.login': 'Sign In',
    'nav.logout': 'Sign Out',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.signUp': 'Sign Up',
    'auth.signUpLink': "Don't have an account? Sign up",
    'auth.signInLink': 'Already have an account? Sign in',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordLink': 'Forgot your password?',
    
    // Admin Panel
    'admin.title': 'Administration Panel',
    'admin.cmsManagement': 'Content Management',
    'admin.sections': 'Sections',
    'admin.pages': 'Pages',
    'admin.userManagement': 'User Management',
    'admin.addSection': 'Add Section',
    'admin.addPage': 'Add Page',
    'admin.sectionTitle': 'Section Title',
    'admin.pageTitle': 'Page Title',
    'admin.slug': 'Slug',
    'admin.content': 'Content',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.visibleToPartners': 'Visible to Partners',
    'admin.visibleToClients': 'Visible to Clients',
    'admin.visibleToEveryone': 'Visible to Everyone',
    'admin.visibleToSpecjalista': 'Visible to Specialists',
    'admin.published': 'Published',
    'admin.unpublished': 'Unpublished',
    'admin.contentManagement': 'Content Management',
    'admin.fonts': 'Fonts',
    'admin.colors': 'Colors',
    'admin.textEditor': 'Text Editor',
    'admin.account': 'Account',
    'admin.users': 'Users',
    'admin.sectionManagement': 'Section Management',
    'admin.addItem': 'Add Item',
    'admin.moveUp': 'Move Up',
    'admin.moveDown': 'Move Down',
    'admin.itemType': 'Item Type',
    'admin.itemTitle': 'Item Title',
    'admin.description': 'Description',
    'admin.url': 'URL',
    'admin.icon': 'Icon',
    'admin.media': 'Media',
    'admin.altText': 'Alt Text',
    'admin.uploadMedia': 'Upload Media',
    'admin.formatting': 'Formatting',
    'admin.textFormatting': 'Text Formatting',
    'admin.titleFormatting': 'Title Formatting',
    'admin.metaTitle': 'Meta Title',
    'admin.metaDescription': 'Meta Description',
    'admin.pagePosition': 'Page Position',
    'admin.pageVisibility': 'Page Visibility',
    'admin.userRole': 'User Role',
    'admin.userEmail': 'User Email',
    'admin.userStatus': 'User Status',
    'admin.confirmationSent': 'Confirmation Sent',
    'admin.emailConfirmed': 'Email Confirmed',
    'admin.created': 'Created',
    'admin.updated': 'Updated',
    'admin.exportUsers': 'Export Users',
    'admin.inviteUser': 'Invite User',
    'admin.loadingUsers': 'Loading users...',
    'admin.loadingPages': 'Loading pages...',
    'admin.noUsers': 'No users',
    'admin.noPages': 'No pages',
    'admin.noSections': 'No sections',
    'admin.noItems': 'No items in this section',
    'admin.main': 'Main',
    'admin.nestedSections': 'Nested sections',
    'admin.addElement': 'Add element',
    'admin.addElementToSection': 'Add element to section',
    'admin.addElementWithCells': 'Add element with cells',
    'admin.editSection': 'Edit section',
    'admin.deleteSection': 'Delete section',
    'admin.editElement': 'Edit element',
    'admin.deleteElement': 'Delete element',
    'admin.addNestedSection': 'Add nested section',
    'admin.editNestedSection': 'Edit nested section',
    'admin.deleteNestedSection': 'Delete nested section',
    'admin.addNewSection': 'Add new section to page',
    'admin.configureSection': 'Configure appearance and content of new section',
    'admin.saveChanges': 'Save changes',
    'admin.elementType': 'Element type',
    'admin.elementTitle': 'Element title',
    'admin.elementDescription': 'Element description',
    'admin.elementCreated': 'Element has been successfully added to section',
    'admin.noElementsInSection': 'No elements in this section',
    'admin.editPage': 'Edit page',
    'admin.editPageSection': 'Edit page section',
    'admin.editPageElement': 'Edit page element',
    
    // Registration
    'auth.eqId': 'EQ ID',
    'auth.role': 'Choose role',
    'auth.roleClient': 'Client',
    'auth.rolePartner': 'Partner',
    'auth.roleSpecialist': 'Specialist',
    'auth.selectRole': 'Select your role',
    'auth.forgotPassword': 'Forgot password',
    'auth.passwordResetSent': 'Password reset link has been sent',
    'auth.enterEmailForReset': 'Enter email address to reset password',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.share': 'Share',
    'common.noContent': 'No content',
    'common.position': 'Position',
    
    // Account
    'account.myAccount': 'My Account',
    'account.profile': 'Profile',
    'account.updateProfile': 'Update Profile',
    
    // Errors
    'error.notFound': 'Page not found',
    'error.forbidden': 'Access denied',
    'error.returnHome': 'Return to Home',
    
    // Share
    'share.section': 'Share section',
    'share.copied': 'Link copied to clipboard!',
    
    // Page errors
    'page.accessDenied': 'Access denied to page',
    'page.contactAdmin': 'This page is available only for users with appropriate permissions. Contact the administrator to gain access.',
    'page.noContent': 'This page has no content yet',
    'page.contentSoon': 'Content will be added soon.',
    'page.back': 'Back',
    
    // Messages
    'messages.accountBlocked': 'Account blocked',
    'messages.accountDeactivated': 'Your account has been deactivated by the administrator. You do not have access to application functions.',
    'messages.contactAdminError': 'If you believe this is an error, contact the system administrator.',
    'messages.welcomeBack': 'Welcome to the Pure Life system!',
    'messages.loginSuccess': 'Successfully logged in',
    'messages.passwordChanged': 'Password changed successfully.',
    'messages.passwordError': 'Failed to change password.',
    
    // Toast messages
    'toast.error': 'Error',
    'toast.success': 'Success',
    'toast.info': 'Information',
    'toast.redirect': 'Redirect',
    'toast.positionChanged': 'Position changed',
    'toast.pageCreated': 'Page created',
    'toast.visibilityUpdated': 'Visibility updated',
    'toast.pageUpdated': 'Page updated',
    'toast.pageDeleted': 'Page deleted',
    'toast.sectionAdded': 'Section added',
    'toast.elementAdded': 'Element added',
    'toast.sectionUpdated': 'Section updated',
    'toast.elementUpdated': 'Element updated',
    'toast.sectionDeleted': 'Section deleted',
    'toast.elementDeleted': 'Element deleted',
    'toast.linkCopied': 'Link copied',
    'toast.textFormatted': 'Text formatted',
    
    // Error messages
    'error.loadClients': 'Failed to load clients.',
    'error.changeRole': 'Failed to change client role.',
    'error.confirmEmail': 'Failed to confirm client email.',
    'error.changeStatus': 'Failed to change client status.',
    'error.currentPassword': 'Enter current password.',
    'error.passwordMismatch': 'Passwords do not match.',
    'error.passwordLength': 'Password must be at least 6 characters.',
    'error.incorrectPassword': 'Current password is incorrect.',
    'error.changePassword': 'Failed to change password.',
    'error.fillAllFields': 'Fill in all fields.',
    'error.createClient': 'Failed to create client.',
    'error.loadCMS': 'Failed to load CMS data.',
    'error.createSection': 'Failed to create section.',
    'error.deleteSection': 'Failed to delete section.',
    'error.changeSectionPosition': 'Failed to change section position.',
    'error.updateSection': 'Failed to update section.',
    'error.addElement': 'Failed to add element.',
    'error.updateElement': 'Failed to update element.',
    'error.deleteElement': 'Failed to delete element.',
    'error.loadPages': 'Failed to load pages.',
    'error.createPage': 'Failed to create page.',
    'error.updatePageVisibility': 'Failed to update page visibility.',
    'error.updatePage': 'Failed to update page.',
    'error.deletePage': 'Failed to delete page.',
    
    // Success messages
    'success.roleChanged': 'Client role has been changed.',
    'success.emailConfirmed': 'Client email has been confirmed.',
    'success.emailAlreadyConfirmed': 'Email was already confirmed.',
    'success.statusChanged': 'Client status has been changed.',
    'success.passwordChanged': 'Password has been changed.',
    'success.clientCreated': 'New client has been created.',
    'success.redirectToAccount': 'You will be redirected to My Account page.',
    'success.sectionCreated': 'New section has been created.',
    'success.sectionDeleted': 'Section has been deleted.',
    'success.sectionMovedUp': 'Section has been moved up.',
    'success.sectionMovedDown': 'Section has been moved down.',
    'success.sectionUpdated': 'Section has been updated.',
    'success.elementAdded': 'Element has been added.',
    'success.elementUpdated': 'Element has been updated.',
    'success.elementDeleted': 'Element has been deleted.',
    'success.pageCreated': 'New page has been successfully created.',
    'success.pageVisibilityUpdated': 'Page visibility has been updated.',
    'success.pageUpdated': 'Page has been updated.',
    'success.pageDeleted': 'Page has been deleted.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('pure-life-language');
      return (saved as Language) || 'pl';
    } catch (error) {
      console.warn('Failed to get language from localStorage, using default');
      return 'pl';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('pure-life-language', language);
      document.documentElement.lang = language;
    } catch (error) {
      console.warn('Failed to save language to localStorage');
    }
  }, [language]);

  const t = (key: string): string => {
    try {
      return translations[language]?.[key] || key;
    } catch (error) {
      console.warn('Translation error:', error);
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    console.warn('useLanguage called outside of LanguageProvider, using default values');
    return defaultContextValue;
  }
  return context;
};