import React, { useEffect, useState, useCallback } from 'react';
import { loadTranslationsCache, getTranslation, invalidateTranslationsCache, TranslationsMap } from '@/hooks/useTranslations';
import { completeTranslationsData } from '@/lib/translationsData';

export type Language = 'pl' | 'de' | 'en' | string;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  refreshTranslations: () => Promise<void>;
}

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

// Default context value to prevent undefined errors during hot reload
const defaultContextValue: LanguageContextType = {
  language: 'pl' as Language,
  setLanguage: () => {},
  t: (key: string) => key,
  refreshTranslations: async () => {}
};

const translations = {
  pl: {
    // Navigation
    'nav.home': 'Strona główna',
    'nav.admin': 'Panel CMS',
    'nav.myAccount': 'Moje konto',
    'nav.login': 'Zaloguj się',
    'nav.logout': 'Wyloguj się',
    
    // Auth
    'auth.signIn': 'Zaloguj się',
    'auth.email': 'Email',
    'auth.password': 'Hasło',
    'auth.confirmPassword': 'Potwierdź hasło',
    'auth.signUp': 'Zarejestruj się',
    'auth.signUpLink': 'Nie masz konta? Zarejestruj się',
    'auth.signInLink': 'Masz już konto? Zaloguj się',
    'auth.resetPassword': 'Resetuj hasło',
    'auth.resetPasswordLink': 'Zapomniałeś hasła?',
    'auth.eqId': 'EQ ID',
    'auth.role': 'Wybierz rolę',
    'auth.roleClient': 'Klient',
    'auth.rolePartner': 'Partner',
    'auth.roleSpecialist': 'Specjalista',
    'auth.selectRole': 'Wybierz swoją rolę',
    'auth.forgotPassword': 'Zapomniałem hasła',
    'auth.passwordResetSent': 'Link do resetowania hasła został wysłany',
    'auth.enterEmailForReset': 'Wprowadź adres email aby zresetować hasło',
    
    // Font Editor
    'fonts.title': 'Czcionki',
    'fonts.editor': 'Edytor czcionek',
    'fonts.description': 'Zarządzaj typografią aplikacji',
    'fonts.selectGoogleFont': 'Wybierz czcionkę Google Fonts',
    'fonts.preview': 'Podgląd czcionki',
    'fonts.sampleHeading': 'Przykładowy nagłówek',
    'fonts.sampleText': 'To jest przykładowy tekst pokazujący jak wygląda wybrana czcionka w różnych rozmiarach. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'fonts.settings': 'Ustawienia czcionki',
    'fonts.headingSize': 'Rozmiar nagłówków',
    'fonts.bodySize': 'Rozmiar tekstu',
    'fonts.lineHeight': 'Wysokość linii',
    'fonts.letterSpacing': 'Odstępy między literami',
    'fonts.apply': 'Zastosuj zmiany',
    'fonts.cancel': 'Anuluj',
    'fonts.loading': 'Ładowanie czcionek...',
    'fonts.noFontsFound': 'Nie znaleziono czcionek',
    'fonts.searchPlaceholder': 'Wyszukaj czcionkę...',
    
    // Color Editor
    'colors.title': 'Kolory',
    'colors.editor': 'Edytor kolorów',
    'colors.description': 'Zarządzaj paletą kolorów aplikacji',
    'colors.primary': 'Kolor główny',
    'colors.secondary': 'Kolor drugorzędny',
    'colors.accent': 'Kolor akcentu',
    'colors.background': 'Tło',
    'colors.text': 'Tekst',
    'colors.preview': 'Podgląd kolorów',
    'colors.resetToDefault': 'Przywróć domyślne',
    'colors.customColor': 'Kolor niestandardowy',
    
    // Text Editor
    'textEditor.title': 'Edytor tekstu',
    'textEditor.description': 'Zarządzaj zawartością tekstową',
    'textEditor.placeholder': 'Wprowadź tekst...',
    
    // Admin Panel
    'admin.title': 'Panel administracyjny',
    'admin.cmsManagement': 'Zarządzanie treścią',
    'admin.sections': 'Sekcje',
    'admin.pages': 'Strony',
    'admin.userManagement': 'Zarządzanie użytkownikami',
    'admin.addSection': 'Dodaj sekcję',
    'admin.addPage': 'Dodaj stronę',
    'admin.sectionTitle': 'Tytuł sekcji',
    'admin.pageTitle': 'Tytuł strony',
    'admin.slug': 'Slug',
    'admin.content': 'Zawartość',
    'admin.save': 'Zapisz',
    'admin.cancel': 'Anuluj',
    'admin.edit': 'Edytuj',
    'admin.delete': 'Usuń',
    'admin.active': 'Aktywna',
    'admin.inactive': 'Nieaktywna',
    'admin.visibleToPartners': 'Widoczne dla partnerów',
    'admin.visibleToClients': 'Widoczne dla klientów',
    'admin.visibleToEveryone': 'Widoczne dla wszystkich',
    'admin.visibleToSpecialists': 'Widoczne dla specjalistów',
    'admin.published': 'Opublikowana',
    'admin.unpublished': 'Nieopublikowana',
    'admin.contentManagement': 'Zarządzanie treścią',
    'admin.fonts': 'Czcionki',
    'admin.colors': 'Kolory',
    'admin.textEditor': 'Edytor tekstu',
    'admin.settings': 'Ustawienia',
    'admin.account': 'Konto',
    'admin.users': 'Użytkownicy',
    'admin.sectionManagement': 'Zarządzanie sekcjami',
    'admin.addItem': 'Dodaj element',
    'admin.moveUp': 'Przesuń w górę',
    'admin.moveDown': 'Przesuń w dół',
    'admin.itemType': 'Typ elementu',
    'admin.itemTitle': 'Tytuł elementu',
    'admin.description': 'Opis',
    'admin.url': 'URL',
    'admin.icon': 'Ikona',
    'admin.media': 'Media',
    'admin.altText': 'Tekst alternatywny',
    'admin.uploadMedia': 'Prześlij media',
    'admin.formatting': 'Formatowanie',
    'admin.textFormatting': 'Formatowanie tekstu',
    'admin.titleFormatting': 'Formatowanie tytułu',
    'admin.metaTitle': 'Meta tytuł',
    'admin.metaDescription': 'Meta opis',
    'admin.pagePosition': 'Pozycja strony',
    'admin.pageVisibility': 'Widoczność strony',
    'admin.userRole': 'Rola użytkownika',
    'admin.userEmail': 'Email użytkownika',
    'admin.userStatus': 'Status użytkownika',
    'admin.confirmationSent': 'Potwierdzenie wysłane',
    'admin.emailConfirmed': 'Email potwierdzony',
    'admin.created': 'Utworzono',
    'admin.updated': 'Zaktualizowano',
    'admin.exportUsers': 'Eksportuj użytkowników',
    'admin.inviteUser': 'Zaproś użytkownika',
    'admin.loadingUsers': 'Ładowanie użytkowników...',
    'admin.loadingPages': 'Ładowanie stron...',
    'admin.noUsers': 'Brak użytkowników',
    'admin.noPages': 'Brak stron',
    'admin.noSections': 'Brak sekcji',
    'admin.noItems': 'Brak elementów w tej sekcji',
    'admin.main': 'Główna',
    'admin.nestedSections': 'Sekcje zagnieżdżone',
    'admin.addElement': 'Dodaj element',
    'admin.addElementToSection': 'Dodaj element do sekcji',
    'admin.addElementWithCells': 'Dodaj element z komórkami',
    'admin.editSection': 'Edytuj sekcję',
    'admin.deleteSection': 'Usuń sekcję',
    'admin.editElement': 'Edytuj element',
    'admin.deleteElement': 'Usuń element',
    'admin.addNestedSection': 'Dodaj sekcję zagnieżdżoną',
    'admin.editNestedSection': 'Edytuj sekcję zagnieżdżoną',
    'admin.deleteNestedSection': 'Usuń sekcję zagnieżdżoną',
    'admin.addNewSection': 'Dodaj nową sekcję do strony',
    'admin.configureSection': 'Skonfiguruj wygląd i zawartość nowej sekcji',
    'admin.saveChanges': 'Zapisz zmiany',
    'admin.elementType': 'Typ elementu',
    'admin.elementTitle': 'Tytuł elementu',
    'admin.elementDescription': 'Opis elementu',
    'admin.elementCreated': 'Element został pomyślnie dodany do sekcji',
    'admin.noElementsInSection': 'Brak elementów w tej sekcji',
    'admin.editPage': 'Edytuj stronę',
    'admin.editPageSection': 'Edytuj sekcję strony',
    'admin.editPageElement': 'Edytuj element strony',
    'admin.deleteUser': 'Usuń użytkownika',
    'admin.confirmDeleteUser': 'Czy na pewno chcesz usunąć tego użytkownika?',
    'admin.deleteUserSuccess': 'Użytkownik został usunięty',
    'admin.deleteUserError': 'Błąd podczas usuwania użytkownika',
    'admin.searchSections': 'Szukaj sekcji...',
    'admin.clearSearch': 'Wyczyść',
    'admin.noSectionsFound': 'Nie znaleziono sekcji pasujących do wyszukiwania',
    'admin.searchUsers': 'Szukaj użytkowników...',
    'admin.noUsersFound': 'Nie znaleziono użytkowników',
    'admin.showing': 'Wyświetlane',
    'admin.of': 'z',
    'admin.totalUsers': 'Łączna liczba klientów',
    
    // Dialog titles
    'dialog.addSection': 'Dodaj nową sekcję',
    'dialog.editSection': 'Edytuj sekcję',
    'dialog.deleteSection': 'Usuń sekcję',
    'dialog.addElement': 'Dodaj nowy element',
    'dialog.editElement': 'Edytuj element',
    'dialog.deleteElement': 'Usuń element',
    'dialog.addPage': 'Dodaj nową stronę',
    'dialog.editPage': 'Edytuj stronę',
    'dialog.deletePage': 'Usuń stronę',
    'dialog.confirmDeleteSection': 'Czy na pewno chcesz usunąć tę sekcję?',
    'dialog.confirmDeleteElement': 'Czy na pewno chcesz usunąć ten element?',
    'dialog.confirmDeletePage': 'Czy na pewno chcesz usunąć tę stronę?',
    
    // Common actions
    'action.save': 'Zapisz',
    'action.cancel': 'Anuluj',
    'action.edit': 'Edytuj',
    'action.delete': 'Usuń',
    'action.add': 'Dodaj',
    'action.create': 'Utwórz',
    'action.update': 'Aktualizuj',
    'action.close': 'Zamknij',
    'action.confirm': 'Potwierdź',
    'action.back': 'Wstecz',
    'action.next': 'Dalej',
    'action.submit': 'Wyślij',
    'action.reset': 'Resetuj',
    
    // MyAccount
    'myAccount.title': 'Moje konto',
    'myAccount.profile': 'Profil',
    'myAccount.changePassword': 'Zmień hasło',
    'myAccount.currentPassword': 'Aktualne hasło',
    'myAccount.newPassword': 'Nowe hasło',
    'myAccount.confirmNewPassword': 'Potwierdź nowe hasło',
    'myAccount.updateProfile': 'Aktualizuj profil',
    'myAccount.accountInfo': 'Informacje o koncie',
    'myAccount.emailAddress': 'Adres email',
    'myAccount.userRole': 'Rola użytkownika',
    'myAccount.accountStatus': 'Status konta',
    'myAccount.memberSince': 'Członek od',
    'myAccount.lastLogin': 'Ostatnie logowanie',
    'myAccount.accountSettings': 'Ustawienia konta',
    'myAccount.notifications': 'Powiadomienia',
    'myAccount.privacy': 'Prywatność',
    'myAccount.security': 'Bezpieczeństwo',
    
    // Success messages - using unique keys to avoid duplicates
    'success.roleChanged': 'Rola klienta została zmieniona.',
    'success.emailConfirmed': 'Email klienta został potwierdzony.',
    'success.emailAlreadyConfirmed': 'Email był już wcześniej potwierdzony.',
    'success.statusChanged': 'Status klienta został zmieniony.',
    'success.passwordChanged': 'Hasło zostało zmienione.',
    'success.clientCreated': 'Nowy klient został utworzony.',
    
    'success.sectionCreated': 'Nowa sekcja została utworzona.',
    'success.sectionDeleted': 'Sekcja została usunięta.',
    'success.sectionMovedUp': 'Sekcja została przesunięta w górę.',
    'success.sectionMovedDown': 'Sekcja została przesunięta w dół.',
    'success.sectionUpdated': 'Sekcja została zaktualizowana.',
    'success.elementAdded': 'Element został dodany.',
    'success.elementUpdated': 'Element został zaktualizowany.',
    'success.elementDeleted': 'Element został pomyślnie usunięty.',
    'success.visibilityUpdated': 'Ustawienia widoczności sekcji zostały zaktualizowane.',
    'success.nestedSectionAdded': 'Sekcja została pomyślnie dodana jako zagnieżdżona w obecnej sekcji',
    'success.pageCreated': 'Nowa strona została pomyślnie utworzona.',
    'success.pageVisibilityUpdated': 'Widoczność strony została zaktualizowana.',
    'success.pageUpdated': 'Strona została zaktualizowana.',
    'success.pageDeleted': 'Strona została usunięta.',
    
    // Error messages - using unique keys to avoid duplicates
    'error.loadPages': 'Nie udało się pobrać stron.',
    'error.addSection': 'Nie udało się dodać sekcji.',
    'error.addElement': 'Nie udało się dodać elementu.',
    'error.updateSection': 'Nie udało się zaktualizować sekcji.',
    'error.updateElement': 'Nie udało się zaktualizować elementu.',
    'error.deleteSection': 'Nie udało się usunąć sekcji.',
    'error.deleteElement': 'Nie udało się usunąć elementu.',
    'error.moveSection': 'Nie udało się przesunąć sekcji.',
    'error.saveCMSData': 'Nie udało się zapisać danych CMS.',
    'error.loadCMSData': 'Nie udało się załadować danych CMS.',
    'error.invalidCredentials': 'Nieprawidłowe dane logowania.',
    'error.networkError': 'Błąd połączenia sieciowego.',
    'error.serverError': 'Błąd serwera.',
    'error.unknownError': 'Wystąpił nieprzewidziany błąd.',
    'error.accessDenied': 'Brak uprawnień dostępu.',
    'error.forbidden': 'Brak dostępu',
    'error.sessionExpired': 'Sesja wygasła. Zaloguj się ponownie.',
    'error.fieldsRequired': 'Wszystkie pola są wymagane.',
    'error.emailInvalid': 'Nieprawidłowy format adresu email.',
    'error.passwordTooShort': 'Hasło musi mieć co najmniej 6 znaków.',
    'error.passwordsNotMatch': 'Hasła nie są identyczne.',
    'error.uploadFailed': 'Nie udało się przesłać pliku.',
    'error.fileTooBig': 'Plik jest za duży.',
    'error.fileTypeNotSupported': 'Nieobsługiwany typ pliku.',
    'error.changeRole': 'Nie udało się zmienić roli klienta.',
    'error.confirmEmail': 'Nie udało się potwierdzić emaila klienta.',
    'error.changeStatus': 'Nie udało się zmienić statusu klienta.',
    'error.currentPassword': 'Podaj aktualne hasło.',
    'error.passwordMismatch': 'Hasła nie są identyczne.',
    'error.passwordLength': 'Hasło musi mieć co najmniej 6 znaków.',
    'error.incorrectPassword': 'Aktualne hasło jest nieprawidłowe.',
    'error.changePassword': 'Nie udało się zmienić hasła.',
    'error.fillAllFields': 'Wypełnij wszystkie pola.',
    'error.createClient': 'Nie udało się utworzyć klienta.',
    'error.loadCMS': 'Nie udało się załadować danych CMS.',
    'error.createSection': 'Nie udało się utworzyć sekcji.',
    'error.createPage': 'Nie udało się utworzyć strony.',
    'error.updatePageVisibility': 'Nie udało się zaktualizować widoczności strony.',
    'error.updatePage': 'Nie udało się zaktualizować strony.',
    'error.deletePage': 'Nie udało się usunąć strony.',
    
    // Additional UI translations
    'ui.viewPage': 'Zobacz stronę',
    'ui.copyLink': 'Kopiuj link',
    'ui.published': 'Opublikowana',
    'ui.adding': 'Dodawaj',
    'ui.enter': 'Wprowadź',
    'ui.description': 'Opis',
    'ui.basic': 'Podstawowe',
    'ui.content': 'Zawartość',
    'ui.editor': 'Edytor',
    'ui.preview': 'Podgląd',
    'ui.client': 'klient',
    'ui.partner': 'partner',
    'ui.position': 'pozycja',
    
    // Toolbar translations
    'toolbar.saving': 'Zapisywanie...',
    'toolbar.saved': 'Zapisane',
    'toolbar.errorSaving': 'Błąd zapisu',
    'toolbar.unsavedChanges': 'Niezapisane zmiany',
    'toolbar.desktopView': 'Widok pulpitu',
    'toolbar.tabletView': 'Widok tabletu', 
    'toolbar.mobileView': 'Widok telefonu',
    'toolbar.preview': 'Podgląd',
    'toolbar.cancel': 'Anuluj',
    'toolbar.save': 'Zapisz',
    'ui.active': 'Aktywna',
    'ui.publish': 'Opublikuj',
    'ui.for': 'Dla',
    'ui.all': 'wszystkich',
    'ui.cancel': 'Anuluj',
    'ui.create': 'Utwórz',
    'ui.sections': 'sekcje',
    'ui.element': 'Element',
    'ui.editPage': 'Edytuj stronę',
    'ui.add': 'Dodaj',
    'ui.title': 'Tytuł',
    'ui.uploadFiles': 'Prześlij pliki',
    'ui.dragDrop': 'Przeciągnij i upuść pliki tutaj lub kliknij, aby wybrać',
    'ui.supportedFormats': 'Obsługiwane formaty',
    'ui.maxFileSize': 'Maksymalny rozmiar pliku',
    'ui.selectedFiles': 'Wybrane pliki',
    'ui.uploading': 'Przesyłanie',
    'ui.uploadSuccess': 'Przesłano pomyślnie',
    'ui.uploadError': 'Błąr przesyłania',
    'ui.removeFile': 'Usuń plik',
    'ui.bold': 'Pogrubienie',
    'ui.italic': 'Kursywa',
    'ui.underline': 'Podkreślenie',
    'ui.link': 'Link',
    'ui.insertImage': 'Wstaw obraz',
    'ui.bulletList': 'Lista punktowana',
    'ui.numberedList': 'Lista numerowana',
    'ui.undo': 'Cofnij',
    'ui.redo': 'Ponów',
    'ui.fontSize': 'Rozmiar czcionki',
    'ui.textColor': 'Kolor tekstu',
    'ui.backgroundColor': 'Kolor tła',
    'ui.alignment': 'Wyrównanie',
    
    // Common
    'common.loading': 'Ładowanie...',
    'common.noContent': 'Brak zawartości',
    
    // Training
    'training.title': 'Akademia',
    'training.description': 'Ukończ wszystkie wymagane szkolenia, aby zdobyć niezbędną wiedzę i certyfikaty.',
    'training.loadingAcademy': 'Ładowanie Akademii...',
    'training.backToHome': 'Strona główna',
    'training.noTrainings': 'Brak dostępnych szkoleń',
    'training.noTrainingsDescription': 'Obecnie nie ma żadnych szkoleń dostępnych dla Twojej roli.',
    'training.progress': 'Postęp',
    'training.lessons': 'lekcji',
    'training.minutes': 'min',
    'training.certificateCompleted': 'Certyfikat ukończenia',
    'training.startTraining': 'Rozpocznij szkolenie',
    'training.continueTraining': 'Kontynuuj szkolenie',
    'training.reviewAgain': 'Przejrzyj ponownie',
    'training.statusNotStarted': 'Nierozpoczęty',
    'training.statusInProgress': 'W trakcie',
    'training.statusCompleted': 'Ukończony',
    'training.statusNoLessons': 'Brak lekcji',
    'training.downloadSuccess': 'Certyfikat został pobrany',
    'training.downloadError': 'Nie udało się pobrać certyfikatu',
    'training.loadError': 'Nie można załadować modułów szkoleniowych',
    
    // Training Module
    'trainingModule.backToTrainings': 'Powrót do szkoleń',
    'trainingModule.loadingTraining': 'Ładowanie szkolenia...',
    'trainingModule.notFound': 'Nie znaleziono szkolenia',
    'trainingModule.notFoundDescription': 'Szkolenie nie istnieje lub nie masz do niego dostępu.',
    'trainingModule.lessons': 'Lekcje',
    'trainingModule.completed': 'Ukończone',
    'trainingModule.inProgress': 'W trakcie',
    'trainingModule.previous': 'Poprzednia',
    'trainingModule.next': 'Następna',
    'trainingModule.finish': 'Zakończ',
    'trainingModule.lessonCompleted': 'Lekcja ukończona!',
    
    // Certificates
    'certificates.assignedRoles': 'Przypisane role',
    'certificates.rolesDescription': 'Wybierz role użytkowników, które będą używać tego szablonu certyfikatu',
    'certificates.noRolesAssigned': 'Brak przypisanych ról',
    'certificates.roleUpdated': 'Role zostały zaktualizowane',
    'certificates.assignedModules': 'Przypisane moduły szkoleniowe',
    'certificates.modulesDescription': 'Wybierz moduły szkoleniowe, dla których będzie używany ten szablon',
    'certificates.noModulesAssigned': 'Wszystkie moduły',
    'certificates.modulesUpdated': 'Moduły zostały zaktualizowane',
    
    // Roles
    'roles.admin': 'Administrator',
    'roles.partner': 'Partner',
    'roles.client': 'Klient',
    'roles.specjalista': 'Specjalista',
    'roles.user': 'Użytkownik',
    'trainingModule.lessonCompletedDescription': 'Pomyślnie ukończyłeś lekcję',
    'trainingModule.moduleCompleted': 'Moduł ukończony!',
    'trainingModule.moduleCompletedDescription': 'Gratulacje! Ukończyłeś wszystkie lekcje w tym module.',
    'trainingModule.accessBlocked': 'Dostęp zablokowany',
    'trainingModule.accessBlockedDescription': 'Musisz ukończyć poprzednią lekcję, aby przejść dalej.',
    'trainingModule.timeWarning': 'Musisz spędzić co najmniej',
    'trainingModule.timeWarningContinue': 'na tej lekcji, aby przejść do następnej.',
    'trainingModule.timeRemaining': 'Pozostało:',
    'trainingModule.of': 'z',
    'trainingModule.lessonCompletedReview': 'Lekcja ukończona - możesz obejrzeć ponownie z pełnymi kontrolkami',
    'trainingModule.errorSaving': 'Nie można załadować danych szkolenia',
    
    // Footer
    'footer.allRightsReserved': 'Wszystkie prawa zastrzeżone.',
    'footer.privacyPolicy': 'Polityka prywatności',
    'footer.terms': 'Regulamin',
    
    // Account
    'account.myAccount': 'Moje konto',
    'account.profile': 'Profil',
    'account.manageAccount': 'Zarządzaj swoim kontem i ustawieniami',
    'account.basicInfo': 'Podstawowe informacje o Twoim koncie',
    'account.accountStatus': 'Status konta',
    'account.userId': 'ID klienta',
    'account.updatePassword': 'Zaktualizuj swoje hasło, aby utrzymać bezpieczeństwo konta',
    'account.blocked': 'Konto zablokowane',
    'account.blockedDescription': 'Twoje konto zostało dezaktywowane przez administratora. Nie masz dostępu do funkcji aplikacji.',
    'account.blockedContact': 'Jeśli uważasz, że to pomyłka, skontaktuj się z administratorem systemu.',
    'account.enterCurrent': 'Wprowadź aktualne hasło',
    'account.enterNew': 'Wprowadź nowe hasło',
    'account.repeatNew': 'Powtórz nowe hasło',
    
    // Errors
    'errors.invalidCredentials': 'Nieprawidłowy email lub hasło',
    'errors.emailNotConfirmed': 'Email nie został potwierdzony. Sprawdź swoją skrzynkę pocztową',
    'errors.userExists': 'Użytkownik z tym adresem email już istnieje',
    'errors.weakPassword': 'Hasło jest za słabe. Użyj minimum 6 znaków',
    'errors.invalidEmail': 'Nieprawidłowy format adresu email',
    'errors.tooManyRequests': 'Zbyt wiele prób logowania. Spróbuj ponownie za chwilę',
    'errors.networkError': 'Problem z połączeniem internetowym. Sprawdź połączenie i spróbuj ponownie',
    'errors.unexpectedError': 'Wystąpił nieoczekiwany błąd. Spróbuj ponownie',
    'errors.passwordsNotMatch': 'Hasła nie są identyczne',
    'errors.eqIdRequired': 'EQ ID jest wymagane',
    'errors.roleRequired': 'Wybór roli jest wymagany',
    'errors.userExistsLogin': 'Użytkownik z tym adresem email już istnieje. Zaloguj się lub sprawdź skrzynkę pocztową.',
    'errors.currentPasswordIncorrect': 'Aktualne hasło jest nieprawidłowe',
    'errors.passwordTooShort': 'Nowe hasło musi mieć minimum 6 znaków',
    'errors.provideCurrentPassword': 'Podaj aktualne hasło',
    'errors.passwordChangeError': 'Wystąpił błąd podczas zmiany hasła',
    'errors.emailForReset': 'Wprowadź adres email aby zresetować hasło',
    'errors.loginError': 'Błąd logowania',
    'errors.signupError': 'Błąd rejestracji',
    'errors.passwordResetError': 'Błąd',
    'errors.passwordResetSuccess': 'Sukces',
    
    // Chat Widget
    'chat.title': 'Asystent Pure Life',
    'chat.open': 'Otwórz czat',
    'chat.close': 'Zamknij czat',
    'chat.clear': 'Wyczyść historię',
    'chat.placeholder': 'Napisz wiadomość...',
    'chat.send': 'Wyślij',
    'chat.welcome': 'Cześć! Jestem asystentem Pure Life. Jak mogę Ci pomóc?',
    
    // Role Preview
    'rolePreview.title': 'Podgląd jako rola',
    'rolePreview.real': 'Rzeczywisty widok',
    'rolePreview.admin': 'Administrator',
    'rolePreview.client': 'Klient',
    'rolePreview.partner': 'Partner',
    'rolePreview.specjalista': 'Specjalista',
    'rolePreview.anonymous': 'Niezalogowany',
    'rolePreview.viewingAs': 'Podgląd jako',
    'rolePreview.reset': 'Powrót',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.admin': 'CMS Panel',
    'nav.myAccount': 'Mein Konto',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',
    
    // Auth
    'auth.signIn': 'Anmelden',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.signUp': 'Registrieren',
    'auth.signUpLink': 'Kein Konto? Registrieren',
    'auth.signInLink': 'Bereits ein Konto? Anmelden',
    'auth.resetPassword': 'Passwort zurücksetzen',
    'auth.resetPasswordLink': 'Passwort vergessen?',
    'auth.eqId': 'EQ ID',
    'auth.role': 'Rolle wählen',
    'auth.roleClient': 'Kunde',
    'auth.rolePartner': 'Partner',
    'auth.roleSpecialist': 'Spezialist',
    'auth.selectRole': 'Wählen Sie Ihre Rolle',
    'auth.forgotPassword': 'Passwort vergessen',
    'auth.passwordResetSent': 'Link zum Zurücksetzen des Passworts wurde gesendet',
    'auth.enterEmailForReset': 'E-Mail-Adresse eingeben, um Passwort zurückzusetzen',
    
    // Font Editor
    'fonts.title': 'Schriftarten',
    'fonts.editor': 'Schriftarten-Editor',
    'fonts.description': 'Verwalten Sie die Typografie der App',
    'fonts.selectGoogleFont': 'Google Fonts auswählen',
    'fonts.preview': 'Schriftart-Vorschau',
    'fonts.sampleHeading': 'Beispiel-Überschrift',
    'fonts.sampleText': 'Dies ist ein Beispieltext, der zeigt, wie die ausgewählte Schriftart in verschiedenen Größen aussieht. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'fonts.settings': 'Schriftart-Einstellungen',
    'fonts.headingSize': 'Überschrift-Größe',
    'fonts.bodySize': 'Text-Größe',
    'fonts.lineHeight': 'Zeilenhöhe',
    'fonts.letterSpacing': 'Buchstabenabstand',
    'fonts.apply': 'Änderungen anwenden',
    'fonts.cancel': 'Abbrechen',
    'fonts.loading': 'Schriftarten laden...',
    'fonts.noFontsFound': 'Keine Schriftarten gefunden',
    'fonts.searchPlaceholder': 'Schriftart suchen...',
    
    // Color Editor
    'colors.title': 'Farben',
    'colors.editor': 'Farben-Editor',
    'colors.description': 'Verwalten Sie die Farbpalette der App',
    'colors.primary': 'Hauptfarbe',
    'colors.secondary': 'Sekundärfarbe',
    'colors.accent': 'Akzentfarbe',
    'colors.background': 'Hintergrund',
    'colors.text': 'Text',
    'colors.preview': 'Farben-Vorschau',
    'colors.resetToDefault': 'Auf Standard zurücksetzen',
    'colors.customColor': 'Benutzerdefinierte Farbe',
    
    // Text Editor
    'textEditor.title': 'Text-Editor',
    'textEditor.description': 'Textinhalte verwalten',
    'textEditor.placeholder': 'Text eingeben...',
    
    // Admin Panel
    'admin.title': 'Administrationsbereich',
    'admin.cmsManagement': 'Inhaltsverwaltung',
    'admin.sections': 'Bereiche',
    'admin.pages': 'Seiten',
    'admin.userManagement': 'Benutzerverwaltung',
    'admin.addSection': 'Bereich hinzufügen',
    'admin.addPage': 'Seite hinzufügen',
    'admin.sectionTitle': 'Bereichstitel',
    'admin.pageTitle': 'Seitentitel',
    'admin.slug': 'Slug',
    'admin.content': 'Inhalt',
    'admin.save': 'Speichern',
    'admin.cancel': 'Abbrechen',
    'admin.edit': 'Bearbeiten',
    'admin.delete': 'Löschen',
    'admin.active': 'Aktiv',
    'admin.inactive': 'Inaktiv',
    'admin.visibleToPartners': 'Sichtbar für Partner',
    'admin.visibleToClients': 'Sichtbar für Kunden',
    'admin.visibleToEveryone': 'Sichtbar für alle',
    'admin.visibleToSpecialists': 'Sichtbar für Spezialisten',
    'admin.published': 'Veröffentlicht',
    'admin.unpublished': 'Unveröffentlicht',
    'admin.contentManagement': 'Inhaltsverwaltung',
    'admin.fonts': 'Schriftarten',
    'admin.colors': 'Farben',
    'admin.textEditor': 'Texteditor',
    'admin.settings': 'Einstellungen',
    'admin.account': 'Konto',
    'admin.users': 'Benutzer',
    'admin.sectionManagement': 'Bereichsverwaltung',
    'admin.addItem': 'Element hinzufügen',
    'admin.moveUp': 'Nach oben verschieben',
    'admin.moveDown': 'Nach unten verschieben',
    'admin.itemType': 'Elementtyp',
    'admin.itemTitle': 'Elementtitel',
    'admin.description': 'Beschreibung',
    'admin.url': 'URL',
    'admin.icon': 'Icon',
    'admin.media': 'Medien',
    'admin.altText': 'Alt-Text',
    'admin.uploadMedia': 'Medien hochladen',
    'admin.formatting': 'Formatierung',
    'admin.textFormatting': 'Textformatierung',
    'admin.titleFormatting': 'Titelformatierung',
    'admin.metaTitle': 'Meta-Titel',
    'admin.metaDescription': 'Meta-Beschreibung',
    'admin.pagePosition': 'Seitenposition',
    'admin.pageVisibility': 'Seitensichtbarkeit',
    'admin.userRole': 'Benutzerrolle',
    'admin.userEmail': 'Benutzer-E-Mail',
    'admin.userStatus': 'Benutzerstatus',
    'admin.confirmationSent': 'Bestätigung gesendet',
    'admin.emailConfirmed': 'E-Mail bestätigt',
    'admin.created': 'Erstellt',
    'admin.updated': 'Aktualisiert',
    'admin.exportUsers': 'Benutzer exportieren',
    'admin.inviteUser': 'Benutzer einladen',
    'admin.loadingUsers': 'Benutzer werden geladen...',
    'admin.loadingPages': 'Seiten werden geladen...',
    'admin.noUsers': 'Keine Benutzer',
    'admin.noPages': 'Keine Seiten',
    'admin.noSections': 'Keine Bereiche',
    'admin.noItems': 'Keine Elemente in diesem Bereich',
    'admin.main': 'Hauptseite',
    'admin.nestedSections': 'Verschachtelte Bereiche',
    'admin.addElement': 'Element hinzufügen',
    'admin.addElementToSection': 'Element zum Bereich hinzufügen',
    'admin.addElementWithCells': 'Element mit Zellen hinzufügen',
    'admin.editSection': 'Bereich bearbeiten',
    'admin.deleteSection': 'Bereich löschen',
    'admin.editElement': 'Element bearbeiten',
    'admin.deleteElement': 'Element löschen',
    'admin.addNestedSection': 'Verschachtelten Bereich hinzufügen',
    'admin.editNestedSection': 'Verschachtelten Bereich bearbeiten',
    'admin.deleteNestedSection': 'Verschachtelten Bereich löschen',
    'admin.addNewSection': 'Neuen Bereich zur Seite hinzufügen',
    'admin.configureSection': 'Aussehen und Inhalt des neuen Bereichs konfigurieren',
    'admin.saveChanges': 'Änderungen speichern',
    'admin.elementType': 'Elementtyp',
    'admin.elementTitle': 'Elementtitel',
    'admin.elementDescription': 'Elementbeschreibung',
    'admin.elementCreated': 'Element wurde erfolgreich zum Bereich hinzugefügt',
    'admin.noElementsInSection': 'Keine Elemente in diesem Bereich',
    'admin.editPage': 'Seite bearbeiten',
    'admin.editPageSection': 'Seitenbereich bearbeiten',
    'admin.editPageElement': 'Seitenelement bearbeiten',
    'admin.deleteUser': 'Benutzer löschen',
    'admin.confirmDeleteUser': 'Möchten Sie diesen Benutzer wirklich löschen?',
    'admin.deleteUserSuccess': 'Benutzer wurde gelöscht',
    'admin.deleteUserError': 'Fehler beim Löschen des Benutzers',
    'admin.searchSections': 'Abschnitte suchen...',
    'admin.clearSearch': 'Löschen',
    'admin.noSectionsFound': 'Keine passenden Abschnitte gefunden',
    'admin.searchUsers': 'Benutzer suchen...',
    'admin.noUsersFound': 'Keine Benutzer gefunden',
    'admin.showing': 'Anzeigen',
    'admin.of': 'von',
    'admin.totalUsers': 'Gesamtzahl der Kunden',
    
    // Dialog titles
    'dialog.addSection': 'Neuen Bereich hinzufügen',
    'dialog.editSection': 'Bereich bearbeiten',
    'dialog.deleteSection': 'Bereich löschen',
    'dialog.addElement': 'Neues Element hinzufügen',
    'dialog.editElement': 'Element bearbeiten',
    'dialog.deleteElement': 'Element löschen',
    'dialog.addPage': 'Neue Seite hinzufügen',
    'dialog.editPage': 'Seite bearbeiten',
    'dialog.deletePage': 'Seite löschen',
    'dialog.confirmDeleteSection': 'Sind Sie sicher, dass Sie diesen Bereich löschen möchten?',
    'dialog.confirmDeleteElement': 'Sind Sie sicher, dass Sie dieses Element löschen möchten?',
    'dialog.confirmDeletePage': 'Sind Sie sicher, dass Sie diese Seite löschen möchten?',
    
    // Common actions
    'action.save': 'Speichern',
    'action.cancel': 'Abbrechen',
    'action.edit': 'Bearbeiten',
    'action.delete': 'Löschen',
    'action.add': 'Hinzufügen',
    'action.create': 'Erstellen',
    'action.update': 'Aktualisieren',
    'action.close': 'Schließen',
    'action.confirm': 'Bestätigen',
    'action.back': 'Zurück',
    'action.next': 'Weiter',
    'action.submit': 'Senden',
    'action.reset': 'Zurücksetzen',
    
    // MyAccount
    'myAccount.title': 'Mein Konto',
    'myAccount.profile': 'Profil',
    'myAccount.changePassword': 'Passwort ändern',
    'myAccount.currentPassword': 'Aktuelles Passwort',
    'myAccount.newPassword': 'Neues Passwort',
    'myAccount.confirmNewPassword': 'Neues Passwort bestätigen',
    'myAccount.updateProfile': 'Profil aktualisieren',
    'myAccount.accountInfo': 'Kontoinformationen',
    'myAccount.emailAddress': 'E-Mail-Adresse',
    'myAccount.userRole': 'Benutzerrolle',
    'myAccount.accountStatus': 'Kontostatus',
    'myAccount.memberSince': 'Mitglied seit',
    'myAccount.lastLogin': 'Letzte Anmeldung',
    'myAccount.accountSettings': 'Kontoeinstellungen',
    'myAccount.notifications': 'Benachrichtigungen',
    'myAccount.privacy': 'Datenschutz',
    'myAccount.security': 'Sicherheit',
    
    // Success messages
    'success.roleChanged': 'Kundenrolle wurde geändert.',
    'success.emailConfirmed': 'Kunden-E-Mail wurde bestätigt.',
    'success.emailAlreadyConfirmed': 'E-Mail war bereits bestätigt.',
    'success.statusChanged': 'Kundenstatus wurde geändert.',
    'success.passwordChanged': 'Passwort wurde geändert.',
    'success.clientCreated': 'Neuer Kunde wurde erstellt.',
    'success.redirectToAccount': 'Sie werden zur Mein Konto-Seite weitergeleitet.',
    'success.sectionCreated': 'Neuer Bereich wurde erstellt.',
    'success.sectionDeleted': 'Bereich wurde gelöscht.',
    'success.sectionMovedUp': 'Bereich wurde nach oben verschoben.',
    'success.sectionMovedDown': 'Bereich wurde nach unten verschoben.',
    'success.sectionUpdated': 'Bereich wurde aktualisiert.',
    'success.elementAdded': 'Element wurde hinzugefügt.',
    'success.elementUpdated': 'Element wurde aktualisiert.',
    'success.elementDeleted': 'Element wurde gelöscht.',
    'success.visibilityUpdated': 'Sichtbarkeitseinstellungen des Bereichs wurden aktualisiert.',
    'success.nestedSectionAdded': 'Bereich wurde erfolgreich als verschachtelter Bereich im aktuellen Bereich hinzugefügt',
    'success.pageCreated': 'Neue Seite wurde erfolgreich erstellt.',
    'success.pageVisibilityUpdated': 'Seitensichtbarkeit wurde aktualisiert.',
    'success.pageUpdated': 'Seite wurde aktualisiert.',
    'success.pageDeleted': 'Seite wurde gelöscht.',
    
    // Error messages
    'error.loadPages': 'Seiten konnten nicht abgerufen werden.',
    'error.addSection': 'Bereich konnte nicht hinzugefügt werden.',
    'error.addElement': 'Element konnte nicht hinzugefügt werden.',
    'error.updateSection': 'Bereich konnte nicht aktualisiert werden.',
    'error.updateElement': 'Element konnte nicht aktualisiert werden.',
    'error.deleteSection': 'Bereich konnte nicht gelöscht werden.',
    'error.deleteElement': 'Element konnte nicht gelöscht werden.',
    'error.moveSection': 'Bereich konnte nicht verschoben werden.',
    'error.saveCMSData': 'CMS-Daten konnten nicht gespeichert werden.',
    'error.loadCMSData': 'CMS-Daten konnten nicht geladen werden.',
    'error.invalidCredentials': 'Ungültige Anmeldedaten.',
    'error.networkError': 'Netzwerkfehler.',
    'error.serverError': 'Serverfehler.',
    'error.unknownError': 'Ein unerwarteter Fehler ist aufgetreten.',
    'error.accessDenied': 'Zugriff verweigert.',
    'error.forbidden': 'Kein Zugriff',
    'error.sessionExpired': 'Sitzung abgelaufen. Bitte melden Sie sich erneut an.',
    'error.fieldsRequired': 'Alle Felder sind erforderlich.',
    'error.emailInvalid': 'Ungültiges E-Mail-Format.',
    'error.passwordTooShort': 'Passwort muss mindestens 6 Zeichen lang sein.',
    'error.passwordsNotMatch': 'Passwörter stimmen nicht überein.',
    'error.uploadFailed': 'Datei-Upload fehlgeschlagen.',
    'error.fileTooBig': 'Datei ist zu groß.',
    'error.fileTypeNotSupported': 'Dateityp wird nicht unterstützt.',
    'error.changeRole': 'Kundenrolle konnte nicht geändert werden.',
    'error.confirmEmail': 'Kunden-E-Mail konnte nicht bestätigt werden.',
    'error.changeStatus': 'Kundenstatus konnte nicht geändert werden.',
    'error.currentPassword': 'Geben Sie das aktuelle Passwort ein.',
    'error.passwordMismatch': 'Passwörter stimmen nicht überein.',
    'error.passwordLength': 'Passwort muss mindestens 6 Zeichen lang sein.',
    'error.incorrectPassword': 'Aktuelles Passwort ist falsch.',
    'error.changePassword': 'Passwort konnte nicht geändert werden.',
    'error.fillAllFields': 'Füllen Sie alle Felder aus.',
    'error.createClient': 'Kunde konnte nicht erstellt werden.',
    'error.loadCMS': 'CMS-Daten konnten nicht geladen werden.',
    'error.createSection': 'Bereich konnte nicht erstellt werden.',
    'error.createPage': 'Seite konnte nicht erstellt werden.',
    'error.updatePageVisibility': 'Seitensichtbarkeit konnte nicht aktualisiert werden.',
    'error.updatePage': 'Seite konnte nicht aktualisiert werden.',
    'error.deletePage': 'Seite konnte nicht gelöscht werden.',
    
    // Additional UI translations
    'ui.viewPage': 'Seite anzeigen',
    'ui.copyLink': 'Link kopieren',
    'ui.published': 'Veröffentlicht',
    'ui.adding': 'Hinzufügen',
    'ui.enter': 'Eingeben',
    'ui.description': 'Beschreibung',
    'ui.basic': 'Grundlegend',
    'ui.content': 'Inhalt',
    'ui.editor': 'Editor',
    'ui.preview': 'Vorschau',
    'ui.client': 'Kunde',
    'ui.partner': 'Partner',
    'ui.position': 'Position',
    'ui.active': 'Aktiv',
    'ui.publish': 'Veröffentlichen',
    'ui.for': 'Für',
    'ui.all': 'alle',
    'ui.cancel': 'Abbrechen',
    'ui.create': 'Erstellen',
    'ui.sections': 'Bereiche',
    'ui.element': 'Element',
    'ui.editPage': 'Seite bearbeiten',
    'ui.add': 'Hinzufügen',
    'ui.title': 'Titel',
    'ui.uploadFiles': 'Dateien hochladen',
    'ui.dragDrop': 'Dateien hier hineinziehen oder klicken zum Auswählen',
    'ui.supportedFormats': 'Unterstützte Formate',
    'ui.maxFileSize': 'Maximale Dateigröße',
    'ui.selectedFiles': 'Ausgewählte Dateien',
    'ui.uploading': 'Hochladen',
    'ui.uploadSuccess': 'Erfolgreich hochgeladen',
    'ui.uploadError': 'Upload-Fehler',
    'ui.removeFile': 'Datei entfernen',
    'ui.bold': 'Fett',
    'ui.italic': 'Kursiv',
    'ui.underline': 'Unterstrichen',
    'ui.link': 'Link',
    'ui.insertImage': 'Bild einfügen',
    'ui.bulletList': 'Aufzählungsliste',
    'ui.numberedList': 'Nummerierte Liste',
    'ui.undo': 'Rückgängig',
    'ui.redo': 'Wiederholen',
    'ui.fontSize': 'Schriftgröße',
    'ui.textColor': 'Textfarbe',
    'ui.backgroundColor': 'Hintergrundfarbe',
    'ui.alignment': 'Ausrichtung',
    
    // Toolbar translations
    'toolbar.saving': 'Speichern...',
    'toolbar.saved': 'Gespeichert',
    'toolbar.errorSaving': 'Speicherfehler',
    'toolbar.unsavedChanges': 'Ungespeicherte Änderungen',
    'toolbar.desktopView': 'Desktop-Ansicht',
    'toolbar.tabletView': 'Tablet-Ansicht',
    'toolbar.mobileView': 'Mobil-Ansicht', 
    'toolbar.preview': 'Vorschau',
    'toolbar.cancel': 'Abbrechen',
    'toolbar.save': 'Speichern',
    
    // Common
    'common.loading': 'Lade...',
    'common.noContent': 'Kein Inhalt',
    
    // Training
    'training.title': 'Akademie',
    'training.description': 'Schließen Sie alle erforderlichen Schulungen ab, um das notwendige Wissen und Zertifikate zu erwerben.',
    'training.loadingAcademy': 'Akademie wird geladen...',
    'training.backToHome': 'Startseite',
    'training.noTrainings': 'Keine Schulungen verfügbar',
    'training.noTrainingsDescription': 'Derzeit sind für Ihre Rolle keine Schulungen verfügbar.',
    'training.progress': 'Fortschritt',
    'training.lessons': 'Lektionen',
    'training.minutes': 'Min',
    'training.certificateCompleted': 'Abschlusszertifikat',
    'training.startTraining': 'Schulung beginnen',
    'training.continueTraining': 'Schulung fortsetzen',
    'training.reviewAgain': 'Erneut ansehen',
    'training.statusNotStarted': 'Nicht begonnen',
    'training.statusInProgress': 'In Bearbeitung',
    'training.statusCompleted': 'Abgeschlossen',
    'training.statusNoLessons': 'Keine Lektionen',
    'training.downloadSuccess': 'Zertifikat wurde heruntergeladen',
    'training.downloadError': 'Zertifikat konnte nicht heruntergeladen werden',
    'training.loadError': 'Schulungsmodule konnten nicht geladen werden',
    
    // Training Module
    'trainingModule.backToTrainings': 'Zurück zu Schulungen',
    'trainingModule.loadingTraining': 'Schulung wird geladen...',
    'trainingModule.notFound': 'Schulung nicht gefunden',
    'trainingModule.notFoundDescription': 'Die Schulung existiert nicht oder Sie haben keinen Zugriff darauf.',
    'trainingModule.lessons': 'Lektionen',
    'trainingModule.completed': 'Abgeschlossen',
    'trainingModule.inProgress': 'In Bearbeitung',
    'trainingModule.previous': 'Vorherige',
    'trainingModule.next': 'Nächste',
    'trainingModule.finish': 'Beenden',
    'trainingModule.lessonCompleted': 'Lektion abgeschlossen!',
    
    // Certificates
    'certificates.assignedRoles': 'Zugewiesene Rollen',
    'certificates.rolesDescription': 'Wählen Sie Benutzerrollen aus, die diese Zertifikatsvorlage verwenden',
    'certificates.noRolesAssigned': 'Keine Rollen zugewiesen',
    'certificates.roleUpdated': 'Rollen wurden aktualisiert',
    
    // Roles
    'roles.admin': 'Administrator',
    'roles.partner': 'Partner',
    'roles.client': 'Kunde',
    'roles.specjalista': 'Spezialist',
    'roles.user': 'Benutzer',
    
    'trainingModule.lessonCompletedDescription': 'Sie haben die Lektion erfolgreich abgeschlossen',
    'trainingModule.moduleCompleted': 'Modul abgeschlossen!',
    'trainingModule.moduleCompletedDescription': 'Herzlichen Glückwunsch! Sie haben alle Lektionen in diesem Modul abgeschlossen.',
    'trainingModule.accessBlocked': 'Zugriff gesperrt',
    'trainingModule.accessBlockedDescription': 'Sie müssen die vorherige Lektion abschließen, um fortzufahren.',
    'trainingModule.timeWarning': 'Sie müssen mindestens',
    'trainingModule.timeWarningContinue': 'mit dieser Lektion verbringen, um zur nächsten zu gelangen.',
    'trainingModule.timeRemaining': 'Verbleibend:',
    'trainingModule.of': 'von',
    'trainingModule.lessonCompletedReview': 'Lektion abgeschlossen - Sie können sie mit vollständigen Steuerelementen erneut ansehen',
    'trainingModule.errorSaving': 'Schulungsdaten konnten nicht geladen werden',
    
    // Footer
    'footer.allRightsReserved': 'Alle Rechte vorbehalten.',
    'footer.privacyPolicy': 'Datenschutz',
    'footer.terms': 'Nutzungsbedingungen',
    
    // Account
    'account.myAccount': 'Mein Konto',
    'account.profile': 'Profil',
    'account.manageAccount': 'Verwalten Sie Ihr Konto und Einstellungen',
    'account.basicInfo': 'Grundlegende Informationen über Ihr Konto',
    'account.accountStatus': 'Kontostatus',
    'account.userId': 'Kunden-ID',
    'account.updatePassword': 'Aktualisieren Sie Ihr Passwort, um die Sicherheit Ihres Kontos zu gewährleisten',
    'account.blocked': 'Konto gesperrt',
    'account.blockedDescription': 'Ihr Konto wurde vom Administrator deaktiviert. Sie haben keinen Zugriff auf die Anwendungsfunktionen.',
    'account.blockedContact': 'Wenn Sie glauben, dass dies ein Fehler ist, kontaktieren Sie den Systemadministrator.',
    'account.enterCurrent': 'Aktuelles Passwort eingeben',
    'account.enterNew': 'Neues Passwort eingeben',
    'account.repeatNew': 'Neues Passwort wiederholen',
    
    // Errors
    'errors.invalidCredentials': 'Ungültige E-Mail oder Passwort',
    'errors.emailNotConfirmed': 'E-Mail wurde nicht bestätigt. Überprüfen Sie Ihr Postfach',
    'errors.userExists': 'Ein Benutzer mit dieser E-Mail-Adresse existiert bereits',
    'errors.weakPassword': 'Passwort ist zu schwach. Verwenden Sie mindestens 6 Zeichen',
    'errors.invalidEmail': 'Ungültiges E-Mail-Format',
    'errors.tooManyRequests': 'Zu viele Anmeldeversuche. Versuchen Sie es in einem Moment erneut',
    'errors.networkError': 'Netzwerkproblem. Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut',
    'errors.unexpectedError': 'Ein unerwarteter Fehler ist aufgetreten. Versuchen Sie es erneut',
    'errors.passwordsNotMatch': 'Passwörter stimmen nicht überein',
    'errors.eqIdRequired': 'EQ ID ist erforderlich',
    'errors.roleRequired': 'Rollenauswahl ist erforderlich',
    'errors.userExistsLogin': 'Ein Benutzer mit dieser E-Mail-Adresse existiert bereits. Melden Sie sich an oder überprüfen Sie Ihr Postfach.',
    'errors.currentPasswordIncorrect': 'Aktuelles Passwort ist falsch',
    'errors.passwordTooShort': 'Neues Passwort muss mindestens 6 Zeichen haben',
    'errors.provideCurrentPassword': 'Geben Sie das aktuelle Passwort ein',
    'errors.passwordChangeError': 'Beim Ändern des Passworts ist ein Fehler aufgetreten',
    'errors.emailForReset': 'Geben Sie die E-Mail-Adresse ein, um das Passwort zurückzusetzen',
    'errors.loginError': 'Anmeldefehler',
    'errors.signupError': 'Registrierungsfehler',
    'errors.passwordResetError': 'Fehler',
    'errors.passwordResetSuccess': 'Erfolg',
    
    // Chat Widget
    'chat.title': 'Pure Life Assistent',
    'chat.open': 'Chat öffnen',
    'chat.close': 'Chat schließen',
    'chat.clear': 'Verlauf löschen',
    'chat.placeholder': 'Nachricht schreiben...',
    'chat.send': 'Senden',
    'chat.welcome': 'Hallo! Ich bin der Pure Life Assistent. Wie kann ich Ihnen helfen?',
    
    // Role Preview
    'rolePreview.title': 'Vorschau als Rolle',
    'rolePreview.real': 'Echte Ansicht',
    'rolePreview.admin': 'Administrator',
    'rolePreview.client': 'Kunde',
    'rolePreview.partner': 'Partner',
    'rolePreview.specjalista': 'Spezialist',
    'rolePreview.anonymous': 'Nicht angemeldet',
    'rolePreview.viewingAs': 'Vorschau als',
    'rolePreview.reset': 'Zurück',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.admin': 'CMS Panel',
    'nav.myAccount': 'My Account',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.signUp': 'Sign Up',
    'auth.signUpLink': "Don't have an account? Sign up",
    'auth.signInLink': 'Already have an account? Sign in',
    'auth.resetPassword': 'Reset Password',
    'auth.resetPasswordLink': 'Forgot your password?',
    'auth.eqId': 'EQ ID',
    'auth.role': 'Select Role',
    'auth.roleClient': 'Client',
    'auth.rolePartner': 'Partner',
    'auth.roleSpecialist': 'Specialist',
    'auth.selectRole': 'Select your role',
    'auth.forgotPassword': 'Forgot Password',
    'auth.passwordResetSent': 'Password reset link has been sent',
    'auth.enterEmailForReset': 'Enter email address to reset password',
    
    // Font Editor
    'fonts.title': 'Fonts',
    'fonts.editor': 'Font Editor',
    'fonts.description': 'Manage application typography',
    'fonts.selectGoogleFont': 'Select Google Font',
    'fonts.preview': 'Font Preview',
    'fonts.sampleHeading': 'Sample Heading',
    'fonts.sampleText': 'This is sample text showing how the selected font looks in different sizes. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    'fonts.settings': 'Font Settings',
    'fonts.headingSize': 'Heading Size',
    'fonts.bodySize': 'Body Size',
    'fonts.lineHeight': 'Line Height',
    'fonts.letterSpacing': 'Letter Spacing',
    'fonts.apply': 'Apply Changes',
    'fonts.cancel': 'Cancel',
    'fonts.loading': 'Loading fonts...',
    'fonts.noFontsFound': 'No fonts found',
    'fonts.searchPlaceholder': 'Search for font...',
    
    // Color Editor
    'colors.title': 'Colors',
    'colors.editor': 'Color Editor',
    'colors.description': 'Manage application color palette',
    'colors.primary': 'Primary Color',
    'colors.secondary': 'Secondary Color',
    'colors.accent': 'Accent Color',
    'colors.background': 'Background',
    'colors.text': 'Text',
    'colors.preview': 'Color Preview',
    'colors.resetToDefault': 'Reset to Default',
    'colors.customColor': 'Custom Color',
    
    // Text Editor
    'textEditor.title': 'Text Editor',
    'textEditor.description': 'Manage text content',
    'textEditor.placeholder': 'Enter text...',
    
    // Admin Panel
    'admin.title': 'Admin Panel',
    'admin.cmsManagement': 'Content Management',
    'admin.sections': 'Sections',
    'admin.pages': 'Pages',
    'admin.userManagement': 'User Management',
    'admin.addSection': 'Add Section',
    'admin.addPage': 'Add Page',
    'admin.sectionTitle': 'Section Title',
    'admin.pageTitle': 'Page Title',
    'admin.slug': 'Slug',
    'admin.content': 'Content',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.visibleToPartners': 'Visible to Partners',
    'admin.visibleToClients': 'Visible to Clients',
    'admin.visibleToEveryone': 'Visible to Everyone',
    'admin.visibleToSpecialists': 'Visible to Specialists',
    'admin.published': 'Published',
    'admin.unpublished': 'Unpublished',
    'admin.contentManagement': 'Content Management',
    'admin.fonts': 'Fonts',
    'admin.colors': 'Colors',
    'admin.textEditor': 'Text Editor',
    'admin.settings': 'Settings',
    'admin.account': 'Account',
    'admin.users': 'Users',
    'admin.sectionManagement': 'Section Management',
    'admin.addItem': 'Add Item',
    'admin.moveUp': 'Move Up',
    'admin.moveDown': 'Move Down',
    'admin.itemType': 'Item Type',
    'admin.itemTitle': 'Item Title',
    'admin.description': 'Description',
    'admin.url': 'URL',
    'admin.icon': 'Icon',
    'admin.media': 'Media',
    'admin.altText': 'Alt Text',
    'admin.uploadMedia': 'Upload Media',
    'admin.formatting': 'Formatting',
    'admin.textFormatting': 'Text Formatting',
    'admin.titleFormatting': 'Title Formatting',
    'admin.metaTitle': 'Meta Title',
    'admin.metaDescription': 'Meta Description',
    'admin.pagePosition': 'Page Position',
    'admin.pageVisibility': 'Page Visibility',
    'admin.userRole': 'User Role',
    'admin.userEmail': 'User Email',
    'admin.userStatus': 'User Status',
    'admin.confirmationSent': 'Confirmation Sent',
    'admin.emailConfirmed': 'Email Confirmed',
    'admin.created': 'Created',
    'admin.updated': 'Updated',
    'admin.exportUsers': 'Export Users',
    'admin.inviteUser': 'Invite User',
    'admin.loadingUsers': 'Loading users...',
    'admin.loadingPages': 'Loading pages...',
    'admin.noUsers': 'No users',
    'admin.noPages': 'No pages',
    'admin.noSections': 'No sections',
    'admin.noItems': 'No items in this section',
    'admin.main': 'Main',
    'admin.nestedSections': 'Nested Sections',
    'admin.addElement': 'Add Element',
    'admin.addElementToSection': 'Add Element to Section',
    'admin.addElementWithCells': 'Add Element with Cells',
    'admin.editSection': 'Edit Section',
    'admin.deleteSection': 'Delete Section',
    'admin.editElement': 'Edit Element',
    'admin.deleteElement': 'Delete Element',
    'admin.addNestedSection': 'Add Nested Section',
    'admin.editNestedSection': 'Edit Nested Section',
    'admin.deleteNestedSection': 'Delete Nested Section',
    'admin.addNewSection': 'Add New Section to Page',
    'admin.configureSection': 'Configure appearance and content of the new section',
    'admin.saveChanges': 'Save Changes',
    'admin.elementType': 'Element Type',
    'admin.elementTitle': 'Element Title',
    'admin.elementDescription': 'Element Description',
    'admin.elementCreated': 'Element has been successfully added to the section',
    'admin.noElementsInSection': 'No elements in this section',
    'admin.editPage': 'Edit Page',
    'admin.editPageSection': 'Edit Page Section',
    'admin.editPageElement': 'Edit Page Element',
    'admin.deleteUser': 'Delete User',
    'admin.confirmDeleteUser': 'Are you sure you want to delete this user?',
    'admin.deleteUserSuccess': 'User deleted successfully',
    'admin.deleteUserError': 'Error deleting user',
    'admin.searchSections': 'Search sections...',
    'admin.clearSearch': 'Clear',
    'admin.noSectionsFound': 'No sections found matching your search',
    'admin.searchUsers': 'Search users...',
    'admin.noUsersFound': 'No users found',
    'admin.showing': 'Showing',
    'admin.of': 'of',
    'admin.totalUsers': 'Total clients',
    
    // Dialog titles
    'dialog.addSection': 'Add New Section',
    'dialog.editSection': 'Edit Section',
    'dialog.deleteSection': 'Delete Section',
    'dialog.addElement': 'Add New Element',
    'dialog.editElement': 'Edit Element',
    'dialog.deleteElement': 'Delete Element',
    'dialog.addPage': 'Add New Page',
    'dialog.editPage': 'Edit Page',
    'dialog.deletePage': 'Delete Page',
    'dialog.confirmDeleteSection': 'Are you sure you want to delete this section?',
    'dialog.confirmDeleteElement': 'Are you sure you want to delete this element?',
    'dialog.confirmDeletePage': 'Are you sure you want to delete this page?',
    
    // Common actions
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.add': 'Add',
    'action.create': 'Create',
    'action.update': 'Update',
    'action.close': 'Close',
    'action.confirm': 'Confirm',
    'action.back': 'Back',
    'action.next': 'Next',
    'action.submit': 'Submit',
    'action.reset': 'Reset',
    
    // MyAccount
    'myAccount.title': 'My Account',
    'myAccount.profile': 'Profile',
    'myAccount.changePassword': 'Change Password',
    'myAccount.currentPassword': 'Current Password',
    'myAccount.newPassword': 'New Password',
    'myAccount.confirmNewPassword': 'Confirm New Password',
    'myAccount.updateProfile': 'Update Profile',
    'myAccount.accountInfo': 'Account Information',
    'myAccount.emailAddress': 'Email Address',
    'myAccount.userRole': 'User Role',
    'myAccount.accountStatus': 'Account Status',
    'myAccount.memberSince': 'Member Since',
    'myAccount.lastLogin': 'Last Login',
    'myAccount.accountSettings': 'Account Settings',
    'myAccount.notifications': 'Notifications',
    'myAccount.privacy': 'Privacy',
    'myAccount.security': 'Security',
    
    // Success messages
    'success.roleChanged': 'Client role has been changed.',
    'success.emailConfirmed': 'Client email has been confirmed.',
    'success.emailAlreadyConfirmed': 'Email was already confirmed.',
    'success.statusChanged': 'Client status has been changed.',
    'success.passwordChanged': 'Password has been changed.',
    'success.clientCreated': 'New client has been created.',
    'success.redirectToAccount': 'You will be redirected to My Account page.',
    'success.sectionCreated': 'New section has been created.',
    'success.sectionDeleted': 'Section has been deleted.',
    'success.sectionMovedUp': 'Section has been moved up.',
    'success.sectionMovedDown': 'Section has been moved down.',
    'success.sectionUpdated': 'Section has been updated.',
    'success.elementAdded': 'Element has been added.',
    'success.elementUpdated': 'Element has been updated.',
    'success.elementDeleted': 'Element has been deleted.',
    'success.visibilityUpdated': 'Section visibility settings have been updated.',
    'success.nestedSectionAdded': 'Section has been successfully added as nested in the current section',
    'success.pageCreated': 'New page has been successfully created.',
    'success.pageVisibilityUpdated': 'Page visibility has been updated.',
    'success.pageUpdated': 'Page has been updated.',
    'success.pageDeleted': 'Page has been deleted.',
    
    // Error messages
    'error.loadPages': 'Failed to load pages.',
    'error.addSection': 'Failed to add section.',
    'error.addElement': 'Failed to add element.',
    'error.updateSection': 'Failed to update section.',
    'error.updateElement': 'Failed to update element.',
    'error.deleteSection': 'Failed to delete section.',
    'error.deleteElement': 'Failed to delete element.',
    'error.moveSection': 'Failed to move section.',
    'error.saveCMSData': 'Failed to save CMS data.',
    'error.loadCMSData': 'Failed to load CMS data.',
    'error.invalidCredentials': 'Invalid login credentials.',
    'error.networkError': 'Network connection error.',
    'error.serverError': 'Server error.',
    'error.unknownError': 'An unexpected error occurred.',
    'error.accessDenied': 'Access denied.',
    'error.forbidden': 'Access forbidden',
    'error.sessionExpired': 'Session expired. Please log in again.',
    'error.fieldsRequired': 'All fields are required.',
    'error.emailInvalid': 'Invalid email format.',
    'error.passwordTooShort': 'Password must be at least 6 characters long.',
    'error.passwordsNotMatch': 'Passwords do not match.',
    'error.uploadFailed': 'File upload failed.',
    'error.fileTooBig': 'File is too big.',
    'error.fileTypeNotSupported': 'File type not supported.',
    'error.changeRole': 'Failed to change client role.',
    'error.confirmEmail': 'Failed to confirm client email.',
    'error.changeStatus': 'Failed to change client status.',
    'error.currentPassword': 'Enter current password.',
    'error.passwordMismatch': 'Passwords do not match.',
    'error.passwordLength': 'Password must be at least 6 characters long.',
    'error.incorrectPassword': 'Current password is incorrect.',
    'error.changePassword': 'Failed to change password.',
    'error.fillAllFields': 'Fill in all fields.',
    'error.createClient': 'Failed to create client.',
    'error.loadCMS': 'Failed to load CMS data.',
    'error.createSection': 'Failed to create section.',
    'error.createPage': 'Failed to create page.',
    'error.updatePageVisibility': 'Failed to update page visibility.',
    'error.updatePage': 'Failed to update page.',
    'error.deletePage': 'Failed to delete page.',
    
    // Additional UI translations
    'ui.viewPage': 'View Page',
    'ui.copyLink': 'Copy Link',
    'ui.published': 'Published',
    'ui.adding': 'Adding',
    'ui.enter': 'Enter',
    'ui.description': 'Description',
    'ui.basic': 'Basic',
    'ui.content': 'Content',
    'ui.editor': 'Editor',
    'ui.preview': 'Preview',
    'ui.client': 'client',
    'ui.partner': 'partner',
    'ui.position': 'position',
    'ui.active': 'Active',
    'ui.publish': 'Publish',
    'ui.for': 'For',
    'ui.all': 'all',
    'ui.cancel': 'Cancel',
    'ui.create': 'Create',
    'ui.sections': 'sections',
    'ui.element': 'Element',
    'ui.editPage': 'Edit Page',
    'ui.add': 'Add',
    'ui.title': 'Title',
    'ui.uploadFiles': 'Upload Files',
    'ui.dragDrop': 'Drag and drop files here or click to select',
    'ui.supportedFormats': 'Supported formats',
    'ui.maxFileSize': 'Maximum file size',
    'ui.selectedFiles': 'Selected files',
    'ui.uploading': 'Uploading',
    'ui.uploadSuccess': 'Successfully uploaded',
    'ui.uploadError': 'Upload error',
    'ui.removeFile': 'Remove file',
    'ui.bold': 'Bold',
    'ui.italic': 'Italic',
    'ui.underline': 'Underline',
    'ui.link': 'Link',
    'ui.insertImage': 'Insert image',
    'ui.bulletList': 'Bullet list',
    'ui.numberedList': 'Numbered list',
    'ui.undo': 'Undo',
    'ui.redo': 'Redo',
    'ui.fontSize': 'Font size',
    'ui.textColor': 'Text color',
    'ui.backgroundColor': 'Background color',
    'ui.alignment': 'Alignment',
    
    // Toolbar translations
    'toolbar.saving': 'Saving...',
    'toolbar.saved': 'Saved',
    'toolbar.errorSaving': 'Save error',
    'toolbar.unsavedChanges': 'Unsaved changes',
    'toolbar.desktopView': 'Desktop view',
    'toolbar.tabletView': 'Tablet view',
    'toolbar.mobileView': 'Mobile view',
    'toolbar.preview': 'Preview',
    'toolbar.cancel': 'Cancel',
    'toolbar.save': 'Save',
    
    // Common
    'common.loading': 'Loading...',
    'common.noContent': 'No content',
    
    // Training
    'training.title': 'Academy',
    'training.description': 'Complete all required trainings to gain the necessary knowledge and certificates.',
    'training.loadingAcademy': 'Loading Academy...',
    'training.backToHome': 'Home',
    'training.noTrainings': 'No trainings available',
    'training.noTrainingsDescription': 'There are currently no trainings available for your role.',
    'training.progress': 'Progress',
    'training.lessons': 'lessons',
    'training.minutes': 'min',
    'training.certificateCompleted': 'Certificate of completion',
    'training.startTraining': 'Start training',
    'training.continueTraining': 'Continue training',
    'training.reviewAgain': 'Review again',
    'training.statusNotStarted': 'Not started',
    'training.statusInProgress': 'In progress',
    'training.statusCompleted': 'Completed',
    'training.statusNoLessons': 'No lessons',
    'training.downloadSuccess': 'Certificate downloaded',
    'training.downloadError': 'Failed to download certificate',
    'training.loadError': 'Unable to load training modules',
    
    // Training Module
    'trainingModule.backToTrainings': 'Back to trainings',
    'trainingModule.loadingTraining': 'Loading training...',
    'trainingModule.notFound': 'Training not found',
    'trainingModule.notFoundDescription': 'The training does not exist or you do not have access to it.',
    'trainingModule.lessons': 'Lessons',
    'trainingModule.completed': 'Completed',
    'trainingModule.inProgress': 'In progress',
    'trainingModule.previous': 'Previous',
    'trainingModule.next': 'Next',
    'trainingModule.finish': 'Finish',
    'trainingModule.lessonCompleted': 'Lesson completed!',
    
    // Certificates
    'certificates.assignedRoles': 'Assigned Roles',
    'certificates.rolesDescription': 'Select user roles that will use this certificate template',
    'certificates.noRolesAssigned': 'No roles assigned',
    'certificates.roleUpdated': 'Roles updated successfully',
    
    // Roles
    'roles.admin': 'Administrator',
    'roles.partner': 'Partner',
    'roles.client': 'Client',
    'roles.specjalista': 'Specialist',
    'roles.user': 'User',
    
    'trainingModule.lessonCompletedDescription': 'You have successfully completed the lesson',
    'trainingModule.moduleCompleted': 'Module completed!',
    'trainingModule.moduleCompletedDescription': 'Congratulations! You have completed all lessons in this module.',
    'trainingModule.accessBlocked': 'Access blocked',
    'trainingModule.accessBlockedDescription': 'You must complete the previous lesson to proceed.',
    'trainingModule.timeWarning': 'You must spend at least',
    'trainingModule.timeWarningContinue': 'on this lesson to proceed to the next one.',
    'trainingModule.timeRemaining': 'Remaining:',
    'trainingModule.of': 'of',
    'trainingModule.lessonCompletedReview': 'Lesson completed - you can watch again with full controls',
    'trainingModule.errorSaving': 'Unable to load training data',
    
    // Footer
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // Account
    'account.myAccount': 'My Account',
    'account.profile': 'Profile',
    'account.manageAccount': 'Manage your account and settings',
    'account.basicInfo': 'Basic information about your account',
    'account.accountStatus': 'Account status',
    'account.userId': 'User ID',
    'account.updatePassword': 'Update your password to maintain account security',
    'account.blocked': 'Account blocked',
    'account.blockedDescription': 'Your account has been deactivated by the administrator. You do not have access to application functions.',
    'account.blockedContact': 'If you believe this is an error, contact the system administrator.',
    'account.enterCurrent': 'Enter current password',
    'account.enterNew': 'Enter new password',
    'account.repeatNew': 'Repeat new password',
    
    // Errors
    'errors.invalidCredentials': 'Invalid email or password',
    'errors.emailNotConfirmed': 'Email not confirmed. Check your inbox',
    'errors.userExists': 'A user with this email address already exists',
    'errors.weakPassword': 'Password is too weak. Use at least 6 characters',
    'errors.invalidEmail': 'Invalid email format',
    'errors.tooManyRequests': 'Too many login attempts. Try again in a moment',
    'errors.networkError': 'Network problem. Check your connection and try again',
    'errors.unexpectedError': 'An unexpected error occurred. Try again',
    'errors.passwordsNotMatch': 'Passwords do not match',
    'errors.eqIdRequired': 'EQ ID is required',
    'errors.roleRequired': 'Role selection is required',
    'errors.userExistsLogin': 'A user with this email address already exists. Log in or check your inbox.',
    'errors.currentPasswordIncorrect': 'Current password is incorrect',
    'errors.passwordTooShort': 'New password must be at least 6 characters',
    'errors.provideCurrentPassword': 'Provide current password',
    'errors.passwordChangeError': 'An error occurred while changing password',
    'errors.emailForReset': 'Enter email address to reset password',
    'errors.loginError': 'Login error',
    'errors.signupError': 'Signup error',
    'errors.passwordResetError': 'Error',
    'errors.passwordResetSuccess': 'Success',
    
    // Chat Widget
    'chat.title': 'Pure Life Assistant',
    'chat.open': 'Open chat',
    'chat.close': 'Close chat',
    'chat.clear': 'Clear history',
    'chat.placeholder': 'Type a message...',
    'chat.send': 'Send',
    'chat.welcome': 'Hello! I am the Pure Life Assistant. How can I help you?',
    
    // Role Preview
    'rolePreview.title': 'Preview as role',
    'rolePreview.real': 'Real view',
    'rolePreview.admin': 'Administrator',
    'rolePreview.client': 'Client',
    'rolePreview.partner': 'Partner',
    'rolePreview.specjalista': 'Specialist',
    'rolePreview.anonymous': 'Anonymous',
    'rolePreview.viewingAs': 'Viewing as',
    'rolePreview.reset': 'Back',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('pure-life-language');
      return (saved as Language) || 'pl';
    } catch (error) {
      console.warn('Failed to get language from localStorage, using default');
      return 'pl';
    }
  });

  const [dbTranslations, setDbTranslations] = useState<TranslationsMap | null>(null);
  const [defaultLang, setDefaultLang] = useState<string>('pl');

  // Load database translations on mount
  useEffect(() => {
    loadTranslationsCache().then(({ translations: t, languages }) => {
      setDbTranslations(t);
      const def = languages.find(l => l.is_default);
      if (def) setDefaultLang(def.code);
    }).catch(err => {
      console.warn('Failed to load translations from database:', err);
    });
  }, []);

  useEffect(() => {
    try {
      localStorage.setItem('pure-life-language', language);
      document.documentElement.lang = language;
    } catch (error) {
      console.warn('Failed to save language to localStorage');
    }
  }, [language]);

  const refreshTranslations = useCallback(async () => {
    invalidateTranslationsCache();
    const { translations: t, languages } = await loadTranslationsCache();
    setDbTranslations(t);
    const def = languages.find(l => l.is_default);
    if (def) setDefaultLang(def.code);
  }, []);

  const t = useCallback((key: string): string => {
    // First try database translation
    const dbValue = getTranslation(language, key, defaultLang);
    if (dbValue) return dbValue;
    
    // Fallback to hardcoded translations in this file
    // @ts-ignore - translations object has dynamic keys
    const localValue = translations[language]?.[key] || translations[defaultLang]?.[key];
    if (localValue) return localValue;
    
    // Fallback to completeTranslationsData (contains elements.*, editor.*, etc.)
    const completeValue = completeTranslationsData[language]?.[key] || completeTranslationsData[defaultLang]?.[key];
    if (completeValue) return completeValue;
    
    return key;
  }, [language, defaultLang, dbTranslations]);

  const contextValue: LanguageContextType = {
    language,
    setLanguage,
    t,
    refreshTranslations
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = React.useContext(LanguageContext);
  if (context === undefined) {
    console.warn('useLanguage must be used within a LanguageProvider, using default values');
    return defaultContextValue;
  }
  return context;
};