/**
 * Statyczna mapa światowych/międzynarodowych dni tematycznych
 * Klucz: MM-DD, Wartość: tablica nazw dni
 */
export const WORLD_DAYS: Record<string, string[]> = {
  // Styczeń
  '01-01': ['Nowy Rok', 'Światowy Dzień Pokoju'],
  '01-04': ['Światowy Dzień Braille\'a'],
  '01-06': ['Święto Trzech Króli'],
  '01-13': ['Dzień Dziadka'],
  '01-21': ['Dzień Babci'],
  '01-24': ['Międzynarodowy Dzień Edukacji'],
  '01-26': ['Światowy Dzień Cła'],
  '01-27': ['Międzynarodowy Dzień Pamięci o Ofiarach Holokaustu'],
  '01-28': ['Światowy Dzień Ochrony Danych Osobowych'],

  // Luty
  '02-02': ['Światowy Dzień Mokradeł', 'Dzień Świstaka'],
  '02-04': ['Światowy Dzień Walki z Rakiem'],
  '02-06': ['Międzynarodowy Dzień Zerowej Tolerancji dla Okaleczania Narządów Płciowych Kobiet'],
  '02-10': ['Światowy Dzień Roślin Strączkowych'],
  '02-11': ['Światowy Dzień Chorego', 'Europejski Dzień Numeru Alarmowego 112'],
  '02-13': ['Światowy Dzień Radia'],
  '02-14': ['Walentynki'],
  '02-17': ['Dzień Kota'],
  '02-20': ['Światowy Dzień Sprawiedliwości Społecznej'],
  '02-21': ['Międzynarodowy Dzień Języka Ojczystego'],

  // Marzec
  '03-01': ['Narodowy Dzień Pamięci Żołnierzy Wyklętych'],
  '03-03': ['Światowy Dzień Dzikiej Przyrody', 'Światowy Dzień Słuchu'],
  '03-08': ['Międzynarodowy Dzień Kobiet'],
  '03-10': ['Dzień Mężczyzn'],
  '03-14': ['Dzień Liczby Pi', 'Międzynarodowy Dzień Rzek'],
  '03-15': ['Światowy Dzień Praw Konsumenta'],
  '03-17': ['Dzień Świętego Patryka'],
  '03-20': ['Międzynarodowy Dzień Szczęścia', 'Pierwszy Dzień Wiosny'],
  '03-21': ['Światowy Dzień Zespołu Downa', 'Światowy Dzień Poezji', 'Międzynarodowy Dzień Lasów'],
  '03-22': ['Światowy Dzień Wody'],
  '03-23': ['Światowy Dzień Meteorologii'],
  '03-24': ['Światowy Dzień Walki z Gruźlicą'],
  '03-25': ['Dzień Waflowy'],
  '03-26': ['Dzień Kwitnącej Wiśni'],
  '03-27': ['Światowy Dzień Teatru'],

  // Kwiecień
  '04-01': ['Prima Aprilis'],
  '04-02': ['Światowy Dzień Świadomości Autyzmu'],
  '04-07': ['Światowy Dzień Zdrowia'],
  '04-08': ['Międzynarodowy Dzień Romów'],
  '04-10': ['Dzień Bezpieczeństwa na Kolei'],
  '04-11': ['Światowy Dzień Choroby Parkinsona'],
  '04-12': ['Międzynarodowy Dzień Lotnictwa i Kosmonautyki'],
  '04-15': ['Światowy Dzień Sztuki'],
  '04-16': ['Światowy Dzień Głosu'],
  '04-18': ['Międzynarodowy Dzień Zabytków'],
  '04-22': ['Światowy Dzień Ziemi'],
  '04-23': ['Światowy Dzień Książki i Praw Autorskich'],
  '04-25': ['Światowy Dzień Malarii'],
  '04-26': ['Światowy Dzień Własności Intelektualnej'],
  '04-28': ['Światowy Dzień Bezpieczeństwa i Ochrony Zdrowia w Pracy'],
  '04-29': ['Międzynarodowy Dzień Tańca'],
  '04-30': ['Międzynarodowy Dzień Jazzu'],

  // Maj
  '05-01': ['Międzynarodowy Dzień Pracy', 'Święto Pracy'],
  '05-02': ['Dzień Flagi Rzeczypospolitej Polskiej'],
  '05-03': ['Święto Konstytucji 3 Maja', 'Światowy Dzień Wolności Prasy'],
  '05-04': ['Dzień Strażaka', 'Dzień Gwiezdnych Wojen'],
  '05-05': ['Światowy Dzień Higieny Rąk'],
  '05-08': ['Światowy Dzień Czerwonego Krzyża'],
  '05-09': ['Dzień Europy'],
  '05-10': ['Światowy Dzień Lupusa'],
  '05-12': ['Międzynarodowy Dzień Pielęgniarek'],
  '05-15': ['Międzynarodowy Dzień Rodziny'],
  '05-17': ['Światowy Dzień Telekomunikacji', 'Międzynarodowy Dzień Przeciw Homofobii'],
  '05-18': ['Międzynarodowy Dzień Muzeów'],
  '05-20': ['Światowy Dzień Pszczół'],
  '05-21': ['Światowy Dzień Różnorodności Kulturowej'],
  '05-22': ['Międzynarodowy Dzień Różnorodności Biologicznej'],
  '05-25': ['Dzień Afryki'],
  '05-26': ['Dzień Matki'],
  '05-28': ['Międzynarodowy Dzień Zabawy'],
  '05-29': ['Międzynarodowy Dzień Sił Pokojowych ONZ'],
  '05-31': ['Światowy Dzień Bez Tytoniu'],

  // Czerwiec
  '06-01': ['Międzynarodowy Dzień Dziecka'],
  '06-03': ['Światowy Dzień Roweru'],
  '06-05': ['Światowy Dzień Środowiska'],
  '06-06': ['Dzień Języka Rosyjskiego ONZ'],
  '06-08': ['Światowy Dzień Oceanów'],
  '06-12': ['Światowy Dzień Przeciwko Pracy Dzieci'],
  '06-14': ['Światowy Dzień Krwiodawcy'],
  '06-15': ['Światowy Dzień Wiatru'],
  '06-17': ['Światowy Dzień Walki z Pustynnieniem'],
  '06-20': ['Światowy Dzień Uchodźcy'],
  '06-21': ['Pierwszy Dzień Lata', 'Światowy Dzień Muzyki', 'Międzynarodowy Dzień Jogi'],
  '06-23': ['Dzień Ojca', 'Międzynarodowy Dzień Wdów'],
  '06-25': ['Dzień Żeglarza'],
  '06-26': ['Międzynarodowy Dzień Przeciw Narkomanii'],
  '06-30': ['Międzynarodowy Dzień Asteroid'],

  // Lipiec
  '07-01': ['Dzień Psa'],
  '07-04': ['Dzień Niepodległości USA'],
  '07-07': ['Światowy Dzień Czekolady'],
  '07-11': ['Światowy Dzień Ludności'],
  '07-15': ['Światowy Dzień Umiejętności Młodzieży'],
  '07-17': ['Światowy Dzień Emoji'],
  '07-18': ['Międzynarodowy Dzień Nelsona Mandeli'],
  '07-20': ['Światowy Dzień Szachów', 'Rocznica Lądowania na Księżycu'],
  '07-26': ['Światowy Dzień Mangrów'],
  '07-28': ['Światowy Dzień Hepatitis'],
  '07-30': ['Międzynarodowy Dzień Przyjaźni'],

  // Sierpień
  '08-01': ['Rocznica Powstania Warszawskiego'],
  '08-05': ['Światowy Dzień Piwa'],
  '08-08': ['Międzynarodowy Dzień Kota'],
  '08-09': ['Międzynarodowy Dzień Ludności Rdzennej'],
  '08-10': ['Światowy Dzień Lwa'],
  '08-12': ['Międzynarodowy Dzień Młodzieży'],
  '08-13': ['Światowy Dzień Leworęcznych'],
  '08-15': ['Święto Wojska Polskiego', 'Wniebowzięcie NMP'],
  '08-19': ['Światowy Dzień Fotografii', 'Światowy Dzień Pomocy Humanitarnej'],
  '08-23': ['Międzynarodowy Dzień Pamięci o Handlu Niewolnikami'],
  '08-26': ['Dzień Psa'],
  '08-29': ['Międzynarodowy Dzień Przeciw Próbom Nuklearnym'],

  // Wrzesień
  '09-01': ['Dzień Wiedzy', 'Rocznica Wybuchu II Wojny Światowej'],
  '09-05': ['Międzynarodowy Dzień Dobroczynności'],
  '09-08': ['Międzynarodowy Dzień Alfabetyzacji'],
  '09-10': ['Światowy Dzień Zapobiegania Samobójstwom'],
  '09-12': ['Dzień Programisty'],
  '09-15': ['Międzynarodowy Dzień Demokracji'],
  '09-16': ['Międzynarodowy Dzień Ochrony Warstwy Ozonowej'],
  '09-17': ['Światowy Dzień Bezpieczeństwa Pacjenta'],
  '09-21': ['Międzynarodowy Dzień Pokoju'],
  '09-22': ['Pierwszy Dzień Jesieni', 'Światowy Dzień Bez Samochodu'],
  '09-23': ['Międzynarodowy Dzień Języków Migowych'],
  '09-25': ['Światowy Dzień Serca'],
  '09-26': ['Europejski Dzień Języków'],
  '09-27': ['Światowy Dzień Turystyki'],
  '09-28': ['Światowy Dzień Wścieklizny', 'Międzynarodowy Dzień Powszechnego Dostępu do Informacji'],
  '09-29': ['Światowy Dzień Serca'],
  '09-30': ['Międzynarodowy Dzień Tłumacza'],

  // Październik
  '10-01': ['Międzynarodowy Dzień Osób Starszych', 'Światowy Dzień Wegetarianizmu'],
  '10-02': ['Międzynarodowy Dzień Bez Przemocy'],
  '10-04': ['Światowy Dzień Zwierząt'],
  '10-05': ['Światowy Dzień Nauczyciela'],
  '10-09': ['Światowy Dzień Poczty'],
  '10-10': ['Światowy Dzień Zdrowia Psychicznego'],
  '10-11': ['Międzynarodowy Dzień Dziewcząt'],
  '10-14': ['Dzień Edukacji Narodowej'],
  '10-15': ['Międzynarodowy Dzień Białej Laski'],
  '10-16': ['Światowy Dzień Żywności'],
  '10-17': ['Międzynarodowy Dzień Walki z Ubóstwem'],
  '10-20': ['Światowy Dzień Statystyki'],
  '10-24': ['Dzień Organizacji Narodów Zjednoczonych'],
  '10-25': ['Dzień Makaronu'],
  '10-27': ['Światowy Dzień Dziedzictwa Audiowizualnego'],
  '10-29': ['Światowy Dzień Internetu'],
  '10-31': ['Halloween'],

  // Listopad
  '11-01': ['Wszystkich Świętych'],
  '11-02': ['Dzień Zaduszny'],
  '11-05': ['Światowy Dzień Świadomości Tsunami'],
  '11-08': ['Międzynarodowy Dzień Radiologii'],
  '11-10': ['Światowy Dzień Nauki dla Pokoju i Rozwoju'],
  '11-11': ['Święto Niepodległości', 'Światowy Dzień Singla'],
  '11-13': ['Światowy Dzień Życzliwości'],
  '11-14': ['Światowy Dzień Cukrzycy'],
  '11-16': ['Międzynarodowy Dzień Tolerancji'],
  '11-17': ['Międzynarodowy Dzień Studenta'],
  '11-19': ['Światowy Dzień Toalet', 'Międzynarodowy Dzień Mężczyzn'],
  '11-20': ['Ogólnopolski Dzień Praw Dziecka'],
  '11-21': ['Światowy Dzień Telewizji', 'Światowy Dzień Filozofii'],
  '11-25': ['Międzynarodowy Dzień Eliminacji Przemocy wobec Kobiet'],
  '11-26': ['Światowy Dzień Oliwki'],
  '11-29': ['Międzynarodowy Dzień Solidarności z Narodem Palestyńskim'],
  '11-30': ['Andrzejki'],

  // Grudzień
  '12-01': ['Światowy Dzień AIDS'],
  '12-02': ['Międzynarodowy Dzień Zniesienia Niewolnictwa'],
  '12-03': ['Międzynarodowy Dzień Osób Niepełnosprawnych'],
  '12-04': ['Barbórka'],
  '12-05': ['Międzynarodowy Dzień Wolontariusza'],
  '12-06': ['Mikołajki'],
  '12-07': ['Międzynarodowy Dzień Lotnictwa Cywilnego'],
  '12-09': ['Międzynarodowy Dzień Przeciw Korupcji'],
  '12-10': ['Międzynarodowy Dzień Praw Człowieka'],
  '12-11': ['Międzynarodowy Dzień Gór'],
  '12-12': ['Dzień Neutralności'],
  '12-14': ['Dzień Majsterkowicza'],
  '12-18': ['Międzynarodowy Dzień Migrantów'],
  '12-20': ['Międzynarodowy Dzień Solidarności Ludzkiej'],
  '12-21': ['Pierwszy Dzień Zimy'],
  '12-24': ['Wigilia Bożego Narodzenia'],
  '12-25': ['Boże Narodzenie'],
  '12-26': ['Drugi Dzień Świąt Bożego Narodzenia'],
  '12-31': ['Sylwester'],
};

/**
 * Zwraca listę światowych/międzynarodowych dni przypadających na dziś
 */
export function getTodayWorldDays(): string[] {
  const now = new Date();
  const key = `${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  return WORLD_DAYS[key] || [];
}
