-- Add new columns for image styling
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS object_fit TEXT DEFAULT 'cover';
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS max_width INTEGER DEFAULT NULL;
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS max_height INTEGER DEFAULT NULL;
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS box_shadow TEXT DEFAULT NULL;
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS border_width INTEGER DEFAULT 0;
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS border_color TEXT DEFAULT NULL;
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS border_style TEXT DEFAULT 'solid';
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS link_target TEXT DEFAULT '_self';
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS lazy_loading BOOLEAN DEFAULT true;
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS hover_scale NUMERIC DEFAULT 1;
ALTER TABLE cms_items ADD COLUMN IF NOT EXISTS hover_opacity INTEGER DEFAULT 100;