-- Insert translation keys for admin.sidebar namespace
INSERT INTO i18n_translations (language_code, namespace, key, value) VALUES
('pl', 'admin.sidebar', 'content', 'Treść'),
('pl', 'admin.sidebar', 'layout', 'Układ stron'),
('pl', 'admin.sidebar', 'appearance', 'Wygląd'),
('pl', 'admin.sidebar', 'usersCategory', 'Użytkownicy'),
('pl', 'admin.sidebar', 'training', 'Szkolenia'),
('pl', 'admin.sidebar', 'trainings', 'Szkolenia'),
('pl', 'admin.sidebar', 'certificates', 'Certyfikaty'),
('pl', 'admin.sidebar', 'resources', 'Zasoby wiedzy'),
('pl', 'admin.sidebar', 'features', 'Funkcje'),
('pl', 'admin.sidebar', 'dailySignal', 'Sygnał dnia'),
('pl', 'admin.sidebar', 'importantInfo', 'Ważne informacje'),
('pl', 'admin.sidebar', 'events', 'Wydarzenia'),
('pl', 'admin.sidebar', 'guestRegistrations', 'Rejestracje gości'),
('pl', 'admin.sidebar', 'communication', 'Komunikacja'),
('pl', 'admin.sidebar', 'translations', 'Tłumaczenia'),
('pl', 'admin.sidebar', 'teamContacts', 'Kontakty zespołu'),
('pl', 'admin.sidebar', 'notifications', 'Powiadomienia'),
('pl', 'admin.sidebar', 'system', 'System'),
('pl', 'admin.sidebar', 'maintenance', 'Tryb konserwacji'),
('pl', 'admin.sidebar', 'cronJobs', 'Zadania Cron'),
('pl', 'admin.sidebar', 'cookies', 'Cookies'),
('pl', 'admin.sidebar', 'email', 'E-mail'),
('pl', 'admin.sidebar', 'compass', 'Kompas AI'),
('pl', 'admin.sidebar', 'home', 'Strona główna'),
('pl', 'admin.sidebar', 'main', 'Główne'),
('pl', 'admin.sidebar', 'pages', 'Strony'),
('pl', 'admin.sidebar', 'colors', 'Kolory'),
('pl', 'admin.sidebar', 'settings', 'Ustawienia'),
('pl', 'admin.sidebar', 'users', 'Użytkownicy'),
('pl', 'admin.sidebar', 'account', 'Konto'),
('pl', 'admin.sidebar', 'logout', 'Wyloguj'),
('pl', 'admin.sidebar', 'support', 'Wsparcie i pomoc'),
('pl', 'admin.sidebar', 'dashboardFooter', 'Stopka dashboardu'),
('pl', 'admin.sidebar', 'adminPanel', 'Panel Administracyjny'),
('pl', 'admin.sidebar', 'administrator', 'Administrator'),

-- Insert translation keys for admin.meetings namespace
('pl', 'admin.meetings', 'title', 'Zarządzanie spotkaniami indywidualnymi'),
('pl', 'admin.meetings', 'description', 'Włącz lub wyłącz możliwość prowadzenia spotkań indywidualnych dla partnerów'),
('pl', 'admin.meetings', 'searchPartner', 'Szukaj partnera...'),
('pl', 'admin.meetings', 'tripartiteMeeting', 'Spotkanie trójstronne'),
('pl', 'admin.meetings', 'partnerConsultation', 'Konsultacje dla partnerów'),
('pl', 'admin.meetings', 'noPartnersFound', 'Nie znaleziono partnerów'),
('pl', 'admin.meetings', 'noPartnersInSystem', 'Brak partnerów w systemie'),
('pl', 'admin.meetings', 'permissionEnabled', 'Uprawnienie zostało włączone'),
('pl', 'admin.meetings', 'permissionDisabled', 'Uprawnienie zostało wyłączone'),

-- Insert translation keys for admin.otp namespace
('pl', 'admin.otp', 'title', 'Zarządzanie kodami OTP'),
('pl', 'admin.otp', 'description', 'Przeglądaj i zarządzaj kodami dostępu do InfoLinków'),
('pl', 'admin.otp', 'loading', 'Ładowanie kodów OTP...'),
('pl', 'admin.otp', 'fetchError', 'Nie udało się pobrać kodów OTP'),
('pl', 'admin.otp', 'invalidateError', 'Nie udało się unieważnić kodu'),
('pl', 'admin.otp', 'invalidateSuccess', 'Kod został unieważniony'),
('pl', 'admin.otp', 'deleteError', 'Nie udało się usunąć kodu'),
('pl', 'admin.otp', 'deleteSuccess', 'Kod został usunięty'),
('pl', 'admin.otp', 'deleteMultipleError', 'Nie udało się usunąć kodów'),
('pl', 'admin.otp', 'deleted', 'Usunięto kodów:'),
('pl', 'admin.otp', 'canOnlyDeleteInvalidated', 'Można usuwać tylko unieważnione lub wygasłe kody'),
('pl', 'admin.otp', 'selectedCodesActive', 'Zaznaczone kody są aktywne - można usuwać tylko unieważnione lub wygasłe kody'),
('pl', 'admin.otp', 'statusActive', 'Aktywny'),
('pl', 'admin.otp', 'statusExpired', 'Wygasł'),
('pl', 'admin.otp', 'statusInvalidated', 'Unieważniony'),
('pl', 'admin.otp', 'filterAll', 'Wszystkie'),
('pl', 'admin.otp', 'filterActive', 'Aktywne'),
('pl', 'admin.otp', 'filterExpired', 'Wygasłe'),
('pl', 'admin.otp', 'filterInvalidated', 'Unieważnione'),
('pl', 'admin.otp', 'searchPlaceholder', 'Szukaj po kodzie, partnerze lub InfoLinku...'),
('pl', 'admin.otp', 'selected', 'Zaznaczono'),
('pl', 'admin.otp', 'toDelete', 'do usunięcia'),
('pl', 'admin.otp', 'deleteSelected', 'Usuń zaznaczone'),
('pl', 'admin.otp', 'noCodesMatchingCriteria', 'Brak kodów spełniających kryteria wyszukiwania'),
('pl', 'admin.otp', 'noCodes', 'Brak wygenerowanych kodów OTP'),
('pl', 'admin.otp', 'code', 'Kod'),
('pl', 'admin.otp', 'sessions', 'Sesje'),
('pl', 'admin.otp', 'expires', 'Wygasa'),
('pl', 'admin.otp', 'noProfile', 'brak profilu'),
('pl', 'admin.otp', 'noData', 'Brak danych'),
('pl', 'admin.otp', 'invalidate', 'Unieważnij'),
('pl', 'admin.otp', 'deleteConfirmTitle', 'Usunąć zaznaczone kody?'),
('pl', 'admin.otp', 'deleteConfirmText', 'Czy na pewno chcesz usunąć zaznaczone kody? Ta operacja jest nieodwracalna. Liczba:'),
('pl', 'admin.otp', 'deleteConfirmPartialText', 'Tylko unieważnione/wygasłe kody zostaną usunięte. Zaznaczono/do usunięcia:'),
('pl', 'admin.otp', 'detailsTitle', 'Szczegóły kodu OTP'),
('pl', 'admin.otp', 'detailsDescription', 'Pełne informacje o kodzie dostępu'),
('pl', 'admin.otp', 'usedSessions', 'Wykorzystane sesje'),
('pl', 'admin.otp', 'createdAt', 'Utworzono'),

-- Common translations
('pl', 'common', 'partner', 'Partner'),
('pl', 'common', 'email', 'Email'),
('pl', 'common', 'refresh', 'Odśwież'),
('pl', 'common', 'cancelSelection', 'Anuluj zaznaczenie'),
('pl', 'common', 'details', 'Szczegóły'),
('pl', 'common', 'delete', 'Usuń'),
('pl', 'common', 'cancel', 'Anuluj'),
('pl', 'common', 'status', 'Status'),
('pl', 'common', 'actions', 'Akcje'),
('pl', 'toast', 'warning', 'Uwaga')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value;