-- Insert translation keys for webinar admin panel (Polish - default)
INSERT INTO i18n_translations (language_code, namespace, key, value) VALUES
-- Webinar form labels
('pl', 'admin', 'webinar.title', 'Tytuł'),
('pl', 'admin', 'webinar.description', 'Opis'),
('pl', 'admin', 'webinar.required', 'Wymagane'),
('pl', 'admin', 'webinar.dateTime', 'Data i godzina'),
('pl', 'admin', 'webinar.type', 'Typ webinaru'),
('pl', 'admin', 'webinar.host', 'Prowadzący'),
('pl', 'admin', 'webinar.duration', 'Czas trwania (minuty)'),
('pl', 'admin', 'webinar.zoomLink', 'Link do webinaru (Zoom/Teams)'),
('pl', 'admin', 'webinar.thumbnailUrl', 'URL miniatury'),
('pl', 'admin', 'webinar.publishImmediately', 'Opublikuj od razu'),
('pl', 'admin', 'webinar.reminders', 'Przypomnienia'),
('pl', 'admin', 'webinar.smsReminder', 'Włącz przypomnienie SMS'),
('pl', 'admin', 'webinar.emailReminder', 'Włącz przypomnienie Email'),
('pl', 'admin', 'webinar.formConfig', 'Konfiguracja formularza rejestracji'),
('pl', 'admin', 'webinar.edit', 'Edytuj Webinar'),
('pl', 'admin', 'webinar.new', 'Nowy Webinar'),
('pl', 'admin', 'webinar.save', 'Zapisz zmiany'),
('pl', 'admin', 'webinar.add', 'Dodaj Webinar'),
('pl', 'admin', 'webinar.saving', 'Zapisywanie...'),
('pl', 'admin', 'webinar.cancel', 'Anuluj'),
('pl', 'admin', 'webinar.addUrl', 'Dodaj'),
('pl', 'admin', 'webinar.selectType', 'Wybierz typ'),
('pl', 'admin', 'webinar.types.business', 'Biznesowy'),
('pl', 'admin', 'webinar.types.product', 'Produktowy'),
('pl', 'admin', 'webinar.types.motivational', 'Motywacyjny'),
('pl', 'admin', 'webinar.types.training', 'Szkoleniowy'),
('pl', 'admin', 'webinar.error.titleRequired', 'Tytuł jest wymagany'),
('pl', 'admin', 'webinar.error.dateRequired', 'Data i godzina są wymagane'),
('pl', 'admin', 'webinar.error.conflict', 'Konflikt czasowy'),
('pl', 'admin', 'webinar.error.conflictDesc', 'W wybranym czasie odbywa się już inne wydarzenie'),
('pl', 'admin', 'webinar.error.saveFailed', 'Nie udało się zapisać webinaru'),
('pl', 'admin', 'webinar.success.updated', 'Webinar został zaktualizowany'),
('pl', 'admin', 'webinar.success.added', 'Webinar został dodany'),
('pl', 'admin', 'webinar.success.thumbnailAdded', 'URL miniatury został dodany'),
-- Registration form editor labels
('pl', 'admin', 'formEditor.formFields', 'Pola formularza'),
('pl', 'admin', 'formEditor.required', 'Wymagane'),
('pl', 'admin', 'formEditor.buttonText', 'Tekst przycisku'),
('pl', 'admin', 'formEditor.successMessage', 'Komunikat sukcesu'),
('pl', 'admin', 'formEditor.preview', 'Podgląd formularza'),
('pl', 'admin', 'formEditor.emailNote', 'Pole Email jest zawsze wymagane i nie może być wyłączone.'),
('pl', 'admin', 'formEditor.defaultSubmitText', 'Zapisz się na webinar'),
('pl', 'admin', 'formEditor.defaultSuccessMessage', 'Dziękujemy za zapisanie się!'),
('pl', 'admin', 'formEditor.defaultSignUp', 'Zapisz się'),
('pl', 'admin', 'formEditor.fields.email', 'Email'),
('pl', 'admin', 'formEditor.fields.firstName', 'Imię'),
('pl', 'admin', 'formEditor.fields.lastName', 'Nazwisko'),
('pl', 'admin', 'formEditor.fields.phone', 'Telefon'),
-- Common labels
('pl', 'common', 'error', 'Błąd'),
('pl', 'common', 'success', 'Sukces')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value;

-- English translations
INSERT INTO i18n_translations (language_code, namespace, key, value) VALUES
('en', 'admin', 'webinar.title', 'Title'),
('en', 'admin', 'webinar.description', 'Description'),
('en', 'admin', 'webinar.required', 'Required'),
('en', 'admin', 'webinar.dateTime', 'Date and time'),
('en', 'admin', 'webinar.type', 'Webinar type'),
('en', 'admin', 'webinar.host', 'Host'),
('en', 'admin', 'webinar.duration', 'Duration (minutes)'),
('en', 'admin', 'webinar.zoomLink', 'Webinar link (Zoom/Teams)'),
('en', 'admin', 'webinar.thumbnailUrl', 'Thumbnail URL'),
('en', 'admin', 'webinar.publishImmediately', 'Publish immediately'),
('en', 'admin', 'webinar.reminders', 'Reminders'),
('en', 'admin', 'webinar.smsReminder', 'Enable SMS reminder'),
('en', 'admin', 'webinar.emailReminder', 'Enable email reminder'),
('en', 'admin', 'webinar.formConfig', 'Registration form configuration'),
('en', 'admin', 'webinar.edit', 'Edit Webinar'),
('en', 'admin', 'webinar.new', 'New Webinar'),
('en', 'admin', 'webinar.save', 'Save changes'),
('en', 'admin', 'webinar.add', 'Add Webinar'),
('en', 'admin', 'webinar.saving', 'Saving...'),
('en', 'admin', 'webinar.cancel', 'Cancel'),
('en', 'admin', 'webinar.addUrl', 'Add'),
('en', 'admin', 'webinar.selectType', 'Select type'),
('en', 'admin', 'webinar.types.business', 'Business'),
('en', 'admin', 'webinar.types.product', 'Product'),
('en', 'admin', 'webinar.types.motivational', 'Motivational'),
('en', 'admin', 'webinar.types.training', 'Training'),
('en', 'admin', 'webinar.error.titleRequired', 'Title is required'),
('en', 'admin', 'webinar.error.dateRequired', 'Date and time are required'),
('en', 'admin', 'webinar.error.conflict', 'Time conflict'),
('en', 'admin', 'webinar.error.conflictDesc', 'Another event is scheduled at this time'),
('en', 'admin', 'webinar.error.saveFailed', 'Failed to save webinar'),
('en', 'admin', 'webinar.success.updated', 'Webinar has been updated'),
('en', 'admin', 'webinar.success.added', 'Webinar has been added'),
('en', 'admin', 'webinar.success.thumbnailAdded', 'Thumbnail URL has been added'),
('en', 'admin', 'formEditor.formFields', 'Form fields'),
('en', 'admin', 'formEditor.required', 'Required'),
('en', 'admin', 'formEditor.buttonText', 'Button text'),
('en', 'admin', 'formEditor.successMessage', 'Success message'),
('en', 'admin', 'formEditor.preview', 'Form preview'),
('en', 'admin', 'formEditor.emailNote', 'Email field is always required and cannot be disabled.'),
('en', 'admin', 'formEditor.defaultSubmitText', 'Sign up for webinar'),
('en', 'admin', 'formEditor.defaultSuccessMessage', 'Thank you for signing up!'),
('en', 'admin', 'formEditor.defaultSignUp', 'Sign up'),
('en', 'admin', 'formEditor.fields.email', 'Email'),
('en', 'admin', 'formEditor.fields.firstName', 'First name'),
('en', 'admin', 'formEditor.fields.lastName', 'Last name'),
('en', 'admin', 'formEditor.fields.phone', 'Phone'),
('en', 'common', 'error', 'Error'),
('en', 'common', 'success', 'Success')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value;