-- Add footer and common translation keys
INSERT INTO public.i18n_translations (language_code, namespace, key, value) VALUES
-- Footer keys for DashboardFooterSection
('pl', 'footer', 'passion', 'Pasja'),
('pl', 'footer', 'passionDescription', 'Wierzymy w siłę naturalnych rozwiązań i dzielimy się nimi z pełnym przekonaniem.'),
('pl', 'footer', 'community', 'Społeczność'),
('pl', 'footer', 'communityDescription', 'Tworzymy zespół ludzi, którzy wspierają się nawzajem w drodze do zdrowia.'),
('pl', 'footer', 'missionTitle', 'Misja'),
('pl', 'footer', 'missionDescription', 'Poszerzać świadomość o naturalnych metodach dbania o zdrowie.'),
('pl', 'footer', 'quote', 'Zmieniamy życie ludzi na lepsze'),
('pl', 'footer', 'missionStatement', 'Naszą misją jest dzielenie się wiedzą o naturalnych sposobach wspierania zdrowia i budowanie społeczności ludzi świadomych swoich wyborów.'),
('pl', 'footer', 'teamTitle', 'Zespół Pure Life'),
('pl', 'footer', 'teamDescription', 'Jesteśmy grupą pasjonatów zdrowego stylu życia, którzy wierzą w moc natury.'),
('pl', 'footer', 'contact', 'Kontakt'),
('pl', 'footer', 'contactDescription', 'Masz pytania? Chętnie pomożemy!'),
('pl', 'footer', 'contactReminder', 'Pamiętaj, że w pierwszej kolejności skontaktuj się ze swoim opiekunem.'),
('pl', 'footer', 'emailSupport', 'Email Support Pure Life'),
('pl', 'footer', 'allRightsReserved', 'Wszelkie prawa zastrzeżone.'),
('pl', 'footer', 'privacyPolicy', 'Polityka prywatności'),
('pl', 'footer', 'terms', 'Regulamin'),
-- Team contacts role/status badges
('pl', 'teamContacts', 'roles.client', 'Klient'),
('pl', 'teamContacts', 'roles.partner', 'Partner'),
('pl', 'teamContacts', 'roles.specjalista', 'Specjalista'),
('pl', 'teamContacts', 'status.active', 'Klient'),
('pl', 'teamContacts', 'status.observation', 'Obserwacja'),
('pl', 'teamContacts', 'status.potentialPartner', 'Pot. partner'),
('pl', 'teamContacts', 'status.potentialSpecialist', 'Pot. specjalista'),
('pl', 'teamContacts', 'status.suspended', 'Wstrzymany'),
('pl', 'teamContacts', 'status.closedSuccess', 'Sukces'),
('pl', 'teamContacts', 'status.closedNotNow', 'Nie teraz'),
('pl', 'teamContacts', 'noContacts', 'Brak kontaktów'),
('pl', 'teamContacts', 'lastContact', 'Ostatni kontakt'),
('pl', 'teamContacts', 'daysAgo', 'dni temu'),
('pl', 'teamContacts', 'notes', 'Notatki'),
('pl', 'teamContacts', 'noNotes', 'Brak notatek'),
('pl', 'teamContacts', 'saveNotes', 'Zapisz notatki'),
('pl', 'teamContacts', 'deleteConfirm', 'Usuń kontakt'),
('pl', 'teamContacts', 'deleteConfirmDesc', 'Czy na pewno chcesz usunąć ten kontakt? Ta operacja jest nieodwracalna.'),
('pl', 'teamContacts', 'addedOn', 'Dodany'),
('pl', 'teamContacts', 'interests', 'Zainteresowania'),
('pl', 'teamContacts', 'notificationsEnabled', 'Powiadomienia włączone'),
('pl', 'teamContacts', 'askForHelp', 'Poproś o pomoc'),
-- Admin panel common texts
('pl', 'admin', 'templates', 'Szablony'),
('pl', 'admin', 'events', 'Zdarzenia'),
('pl', 'admin', 'logs', 'Logi'),
('pl', 'admin', 'configuration', 'Konfiguracja'),
('pl', 'admin', 'newTemplate', 'Nowy szablon'),
('pl', 'admin', 'editTemplate', 'Edytuj szablon'),
('pl', 'admin', 'preview', 'Podgląd'),
('pl', 'admin', 'duplicate', 'Duplikuj'),
('pl', 'admin', 'activate', 'Aktywuj'),
('pl', 'admin', 'deactivate', 'Dezaktywuj'),
('pl', 'admin', 'sendTest', 'Wyślij test'),
('pl', 'admin', 'noTemplates', 'Brak szablonów'),
('pl', 'admin', 'noLogs', 'Brak logów'),
('pl', 'admin', 'loading', 'Ładowanie...'),
('pl', 'admin', 'retry', 'Ponów'),
('pl', 'admin', 'refresh', 'Odśwież'),
('pl', 'admin', 'export', 'Eksportuj'),
('pl', 'admin', 'import', 'Importuj')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();