
-- Add missing translation keys for dashboard, footer, common, and role namespaces
INSERT INTO i18n_translations (language_code, namespace, key, value) VALUES
-- Footer translations PL
('pl', 'footer', 'passion', 'Pasja'),
('pl', 'footer', 'passionDescription', 'Wierzymy w siłę naturalnych rozwiązań i dzielimy się nimi z pełnym przekonaniem.'),
('pl', 'footer', 'community', 'Społeczność'),
('pl', 'footer', 'communityDescription', 'Tworzymy zespół ludzi, którzy wspierają się nawzajem w drodze do zdrowia.'),
('pl', 'footer', 'missionTitle', 'Misja'),
('pl', 'footer', 'missionDescription', 'Poszerzać świadomość o naturalnych metodach dbania o zdrowie.'),
('pl', 'footer', 'quote', 'Zmieniamy życie ludzi na lepsze'),
('pl', 'footer', 'missionStatement', 'Naszą misją jest dzielenie się wiedzą o naturalnych sposobach wspierania zdrowia i budowanie społeczności ludzi świadomych swoich wyborów.'),
('pl', 'footer', 'teamTitle', 'Zespół Pure Life'),
('pl', 'footer', 'teamDescription', 'Jesteśmy grupą pasjonatów zdrowego stylu życia, którzy wierzą w moc natury.'),
('pl', 'footer', 'contact', 'Kontakt'),
('pl', 'footer', 'contactDescription', 'Masz pytania? Chętnie pomożemy!'),
('pl', 'footer', 'contactReminder', 'Pamiętaj, że w pierwszej kolejności skontaktuj się ze swoim opiekunem.'),
('pl', 'footer', 'emailSupport', 'Email Support Pure Life'),
('pl', 'footer', 'allRightsReserved', 'Wszystkie prawa zastrzeżone'),
('pl', 'footer', 'privacyPolicy', 'Polityka prywatności'),
('pl', 'footer', 'terms', 'Regulamin'),
-- Dashboard translations PL
('pl', 'dashboard', 'comingSoon', 'Wkrótce'),
('pl', 'dashboard', 'download', 'Pobierz'),
('pl', 'dashboard', 'goTo', 'Przejdź'),
('pl', 'dashboard', 'viewAllContacts', 'Zobacz wszystkie kontakty'),
-- Common translations PL
('pl', 'common', 'close', 'Zamknij'),
('pl', 'common', 'edit', 'Edytuj'),
('pl', 'common', 'delete', 'Usuń'),
('pl', 'common', 'preview', 'Podgląd'),
('pl', 'common', 'download', 'Pobierz'),
('pl', 'common', 'save', 'Zapisz'),
('pl', 'common', 'history', 'Historia'),
('pl', 'common', 'cancel', 'Anuluj'),
-- Role translations PL
('pl', 'role', 'client', 'Klient'),
('pl', 'role', 'partner', 'Partner'),
('pl', 'role', 'specialist', 'Specjalista'),
-- Auth error translations PL
('pl', 'auth', 'errors.invalidCredentials', 'Nieprawidłowy email lub hasło'),
('pl', 'auth', 'errors.emailNotConfirmed', 'Email nie został potwierdzony. Sprawdź swoją skrzynkę pocztową'),
('pl', 'auth', 'errors.userExists', 'Użytkownik z tym adresem email już istnieje'),
('pl', 'auth', 'errors.weakPassword', 'Hasło nie spełnia wymagań bezpieczeństwa (min. 8 znaków, wielka i mała litera, cyfra, znak specjalny)'),
('pl', 'auth', 'errors.invalidEmail', 'Nieprawidłowy format adresu email'),
('pl', 'auth', 'errors.tooManyRequests', 'Zbyt wiele prób logowania. Spróbuj ponownie za chwilę'),
('pl', 'auth', 'errors.networkError', 'Problem z połączeniem internetowym. Sprawdź połączenie i spróbuj ponownie'),
('pl', 'auth', 'errors.eqIdExists', 'Użytkownik z tym numerem EQ ID już istnieje w systemie'),
('pl', 'auth', 'errors.unexpectedError', 'Wystąpił nieoczekiwany błąd. Spróbuj ponownie'),
('pl', 'auth', 'errors.userNotFound', 'Nie znaleziono użytkownika z podanym EQ ID'),
('pl', 'auth', 'errors.userSearchError', 'Błąd podczas wyszukiwania użytkownika'),
('pl', 'auth', 'errors.passwordNotMatch', 'Hasła nie są identyczne'),
('pl', 'auth', 'errors.passwordRequirements', 'Hasło nie spełnia wszystkich wymagań bezpieczeństwa'),
('pl', 'auth', 'errors.eqIdRequired', 'EQ ID jest wymagane'),
('pl', 'auth', 'errors.roleRequired', 'Wybór roli jest wymagany'),
('pl', 'auth', 'errors.phoneRequired', 'Numer telefonu jest wymagany'),
('pl', 'auth', 'errors.phoneInvalid', 'Nieprawidłowy format numeru telefonu'),
('pl', 'auth', 'errors.guardianRequired', 'Musisz wybrać opiekuna z listy'),
-- Auth labels PL
('pl', 'auth', 'emailOrEqId', 'Email lub EQ ID'),
('pl', 'auth', 'enterEmailOrEqId', 'Wprowadź email lub EQ ID'),
('pl', 'auth', 'firstName', 'Imię'),
('pl', 'auth', 'lastName', 'Nazwisko'),
('pl', 'auth', 'phoneNumber', 'Numer telefonu'),
('pl', 'auth', 'enterFirstName', 'Wprowadź imię'),
('pl', 'auth', 'enterLastName', 'Wprowadź nazwisko'),
('pl', 'auth', 'enterEqId', 'Wprowadź EQ ID'),
-- Auth password requirements PL
('pl', 'auth', 'passwordRequirements', 'Wymagania hasła:'),
('pl', 'auth', 'requirements.minLength', 'Minimum 8 znaków'),
('pl', 'auth', 'requirements.uppercase', 'Minimum 1 wielka litera (A-Z)'),
('pl', 'auth', 'requirements.lowercase', 'Minimum 1 mała litera (a-z)'),
('pl', 'auth', 'requirements.number', 'Minimum 1 cyfra (0-9)'),
('pl', 'auth', 'requirements.special', 'Minimum 1 znak specjalny (!@#$%...)'),
-- Auth toast messages PL
('pl', 'toast', 'loginError', 'Błąd logowania'),
('pl', 'toast', 'loginSuccess', 'Zalogowano pomyślnie'),
('pl', 'toast', 'registrationError', 'Błąd rejestracji'),
('pl', 'toast', 'accountActivated', 'Konto aktywowane'),
('pl', 'toast', 'accountActivatedDesc', 'Twoje konto zostało pomyślnie aktywowane. Możesz się teraz zalogować.'),
('pl', 'toast', 'welcomeMessage', 'Witaj w systemie Pure Life!'),
('pl', 'toast', 'success', 'Sukces'),
('pl', 'toast', 'error', 'Błąd'),
('pl', 'toast', 'saved', 'Zapisano'),
('pl', 'toast', 'deleted', 'Usunięto'),
('pl', 'toast', 'added', 'Dodano'),
('pl', 'toast', 'copied', 'Skopiowano!'),
('pl', 'toast', 'copyError', 'Błąd kopiowania'),
('pl', 'toast', 'loadError', 'Nie udało się załadować'),
('pl', 'toast', 'saveError', 'Nie udało się zapisać'),
('pl', 'toast', 'deleteError', 'Nie udało się usunąć'),
-- Auth dialog texts PL
('pl', 'auth', 'registrationSuccess', 'Rejestracja pomyślna!'),
('pl', 'auth', 'checkEmail', 'Sprawdź swoją skrzynkę e-mail'),
('pl', 'auth', 'activationLinkSent', 'Na adres została wysłana wiadomość z linkiem aktywacyjnym.'),
('pl', 'auth', 'checkSpam', 'Jeśli nie widzisz wiadomości, sprawdź folder SPAM'),
('pl', 'auth', 'understood', 'Zrozumiałem'),
('pl', 'auth', 'resendEmail', 'Wyślij ponownie'),
('pl', 'auth', 'sending', 'Wysyłanie...'),
('pl', 'auth', 'backToLogin', 'Powrót do logowania'),
-- Team contacts table translations PL
('pl', 'teamContacts', 'deleteTitle', 'Usuń kontakt'),
('pl', 'teamContacts', 'deleteConfirmation', 'Czy na pewno chcesz usunąć ten kontakt? Ta akcja jest nieodwracalna.'),
('pl', 'teamContacts', 'noContacts', 'Brak kontaktów. Dodaj pierwszy kontakt.'),
('pl', 'teamContacts', 'firstName', 'Imię'),
('pl', 'teamContacts', 'lastName', 'Nazwisko'),
('pl', 'teamContacts', 'role', 'Rola'),
('pl', 'teamContacts', 'status', 'Status'),
('pl', 'teamContacts', 'dateAdded', 'Data dodania'),
('pl', 'teamContacts', 'actions', 'Akcje'),
('pl', 'teamContacts', 'active', 'Aktywny'),
('pl', 'teamContacts', 'inactive', 'Nieaktywny'),
('pl', 'teamContacts', 'suspended', 'Wstrzymany'),
('pl', 'teamContacts', 'success', 'Sukces'),
('pl', 'teamContacts', 'notNow', 'Nie teraz')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value;
