-- Add missing translation keys for auth, toast, and requirements
INSERT INTO public.i18n_translations (language_code, namespace, key, value) VALUES
-- Auth errors
('pl', 'auth', 'errors.invalidCredentials', 'Nieprawidłowy email lub hasło'),
('pl', 'auth', 'errors.emailNotConfirmed', 'Email nie został potwierdzony. Sprawdź swoją skrzynkę pocztową i kliknij link aktywacyjny.'),
('pl', 'auth', 'errors.userExists', 'Użytkownik z tym adresem email już istnieje'),
('pl', 'auth', 'errors.weakPassword', 'Hasło nie spełnia wymagań bezpieczeństwa'),
('pl', 'auth', 'errors.invalidEmail', 'Nieprawidłowy format adresu email'),
('pl', 'auth', 'errors.tooManyRequests', 'Zbyt wiele prób logowania. Spróbuj ponownie za chwilę.'),
('pl', 'auth', 'errors.networkError', 'Problem z połączeniem internetowym. Sprawdź połączenie i spróbuj ponownie.'),
('pl', 'auth', 'errors.eqIdExists', 'Użytkownik z tym numerem EQ ID już istnieje'),
('pl', 'auth', 'errors.unexpected', 'Wystąpił nieoczekiwany błąd. Spróbuj ponownie.'),
('pl', 'auth', 'errors.guardianNotFound', 'Nie znaleziono opiekuna o podanym EQ ID'),
('pl', 'auth', 'errors.cannotBeOwnGuardian', 'Nie możesz być własnym opiekunem'),
-- Auth form labels
('pl', 'auth', 'emailOrEqId', 'Email lub EQ ID'),
('pl', 'auth', 'enterEmailOrEqId', 'Wprowadź email lub EQ ID'),
('pl', 'auth', 'firstName', 'Imię'),
('pl', 'auth', 'lastName', 'Nazwisko'),
('pl', 'auth', 'phoneNumber', 'Numer telefonu'),
('pl', 'auth', 'enterFirstName', 'Wprowadź imię'),
('pl', 'auth', 'enterLastName', 'Wprowadź nazwisko'),
('pl', 'auth', 'enterPhoneNumber', 'Wprowadź numer telefonu'),
('pl', 'auth', 'eqId', 'EQ ID'),
('pl', 'auth', 'enterEqId', 'Wprowadź EQ ID'),
('pl', 'auth', 'eqIdOptional', 'EQ ID (opcjonalne)'),
('pl', 'auth', 'guardian', 'Opiekun'),
('pl', 'auth', 'searchGuardian', 'Szukaj opiekuna po imieniu, nazwisku lub EQ ID'),
('pl', 'auth', 'noGuardianFound', 'Nie znaleziono opiekuna'),
('pl', 'auth', 'selectedGuardian', 'Wybrany opiekun'),
('pl', 'auth', 'changeGuardian', 'Zmień'),
-- Password requirements
('pl', 'auth', 'requirements.title', 'Wymagania hasła:'),
('pl', 'auth', 'requirements.minLength', 'Minimum 8 znaków'),
('pl', 'auth', 'requirements.uppercase', 'Minimum 1 wielka litera (A-Z)'),
('pl', 'auth', 'requirements.lowercase', 'Minimum 1 mała litera (a-z)'),
('pl', 'auth', 'requirements.number', 'Minimum 1 cyfra (0-9)'),
('pl', 'auth', 'requirements.special', 'Minimum 1 znak specjalny (!@#$%^&*(),.?":{}|<>)'),
-- Auth dialogs and buttons
('pl', 'auth', 'registrationSuccess', 'Rejestracja pomyślna!'),
('pl', 'auth', 'checkEmailTitle', 'Sprawdź swoją skrzynkę e-mail'),
('pl', 'auth', 'activationLinkSent', 'Na adres {email} została wysłana wiadomość z linkiem aktywacyjnym.'),
('pl', 'auth', 'checkSpam', 'Jeśli nie widzisz wiadomości, sprawdź folder SPAM'),
('pl', 'auth', 'understood', 'Zrozumiałem'),
('pl', 'auth', 'resendEmail', 'Wyślij ponownie'),
('pl', 'auth', 'sending', 'Wysyłanie...'),
('pl', 'auth', 'backToLogin', 'Powrót do logowania'),
('pl', 'auth', 'forgotPassword', 'Zapomniałeś hasła?'),
('pl', 'auth', 'resetPasswordTitle', 'Resetowanie hasła'),
('pl', 'auth', 'resetPasswordDesc', 'Podaj adres e-mail powiązany z Twoim kontem. Wyślemy Ci link do zresetowania hasła.'),
('pl', 'auth', 'sendResetLink', 'Wyślij link resetujący'),
('pl', 'auth', 'cancel', 'Anuluj'),
('pl', 'auth', 'loggingIn', 'Logowanie...'),
('pl', 'auth', 'registering', 'Rejestrowanie...'),
('pl', 'auth', 'noAccount', 'Nie masz konta?'),
('pl', 'auth', 'haveAccount', 'Masz już konto?'),
('pl', 'auth', 'registerHere', 'Zarejestruj się'),
('pl', 'auth', 'loginHere', 'Zaloguj się'),
('pl', 'auth', 'welcomeBack', 'Witaj ponownie'),
('pl', 'auth', 'loginToAccount', 'Zaloguj się do swojego konta'),
('pl', 'auth', 'createAccount', 'Utwórz konto'),
('pl', 'auth', 'joinCommunity', 'Dołącz do społeczności Pure Life'),
-- Auth toast messages
('pl', 'auth', 'toast.loginError', 'Błąd logowania'),
('pl', 'auth', 'toast.loginSuccess', 'Zalogowano pomyślnie'),
('pl', 'auth', 'toast.registrationError', 'Błąd rejestracji'),
('pl', 'auth', 'toast.registrationSuccess', 'Rejestracja pomyślna'),
('pl', 'auth', 'toast.resetEmailSent', 'Link do resetowania hasła został wysłany'),
('pl', 'auth', 'toast.resetEmailError', 'Nie udało się wysłać emaila'),
('pl', 'auth', 'toast.activationResent', 'E-mail aktywacyjny został wysłany ponownie'),
('pl', 'auth', 'toast.activationResendError', 'Nie udało się wysłać emaila aktywacyjnego'),
('pl', 'auth', 'toast.accountActivated', 'Konto aktywowane'),
('pl', 'auth', 'toast.welcomeToPureLife', 'Witamy w Pure Life!'),
-- Additional toast keys
('pl', 'toast', 'saved', 'Zapisano'),
('pl', 'toast', 'deleted', 'Usunięto'),
('pl', 'toast', 'added', 'Dodano'),
('pl', 'toast', 'copied', 'Skopiowano'),
('pl', 'toast', 'copyError', 'Błąd kopiowania'),
('pl', 'toast', 'noPermission', 'Brak uprawnień'),
('pl', 'toast', 'loadError', 'Nie udało się załadować'),
('pl', 'toast', 'saveError', 'Nie udało się zapisać'),
('pl', 'toast', 'deleteError', 'Nie udało się usunąć'),
('pl', 'toast', 'fixedLayout', 'Naprawiono układ'),
('pl', 'toast', 'sectionMoved', 'Sekcja przeniesiona'),
('pl', 'toast', 'sectionsSwapped', 'Sekcje zamienione'),
('pl', 'toast', 'cannotNestRows', 'Nie można zagnieżdżać wierszy'),
('pl', 'toast', 'emailSent', 'Email wysłany'),
('pl', 'toast', 'emailError', 'Błąd wysyłania emaila'),
('pl', 'toast', 'updated', 'Zaktualizowano'),
('pl', 'toast', 'created', 'Utworzono'),
('pl', 'toast', 'activated', 'Aktywowano'),
('pl', 'toast', 'deactivated', 'Dezaktywowano'),
('pl', 'toast', 'approved', 'Zatwierdzono'),
('pl', 'toast', 'rejected', 'Odrzucono'),
('pl', 'toast', 'uploaded', 'Przesłano'),
('pl', 'toast', 'uploadError', 'Błąd przesyłania'),
('pl', 'toast', 'downloadError', 'Błąd pobierania'),
('pl', 'toast', 'connectionError', 'Błąd połączenia'),
('pl', 'toast', 'validationError', 'Błąd walidacji'),
('pl', 'toast', 'requiredFields', 'Wypełnij wymagane pola'),
('pl', 'toast', 'invalidData', 'Nieprawidłowe dane'),
('pl', 'toast', 'operationSuccess', 'Operacja zakończona pomyślnie'),
('pl', 'toast', 'operationError', 'Operacja nie powiodła się'),
-- Common UI keys that might be missing
('pl', 'common', 'loading', 'Ładowanie...'),
('pl', 'common', 'saving', 'Zapisywanie...'),
('pl', 'common', 'deleting', 'Usuwanie...'),
('pl', 'common', 'sending', 'Wysyłanie...'),
('pl', 'common', 'processing', 'Przetwarzanie...'),
('pl', 'common', 'confirm', 'Potwierdź'),
('pl', 'common', 'yes', 'Tak'),
('pl', 'common', 'no', 'Nie'),
('pl', 'common', 'ok', 'OK'),
('pl', 'common', 'close', 'Zamknij'),
('pl', 'common', 'back', 'Wstecz'),
('pl', 'common', 'next', 'Dalej'),
('pl', 'common', 'previous', 'Poprzedni'),
('pl', 'common', 'search', 'Szukaj'),
('pl', 'common', 'filter', 'Filtruj'),
('pl', 'common', 'sort', 'Sortuj'),
('pl', 'common', 'refresh', 'Odśwież'),
('pl', 'common', 'reset', 'Resetuj'),
('pl', 'common', 'clear', 'Wyczyść'),
('pl', 'common', 'selectAll', 'Zaznacz wszystko'),
('pl', 'common', 'deselectAll', 'Odznacz wszystko'),
('pl', 'common', 'noResults', 'Brak wyników'),
('pl', 'common', 'noData', 'Brak danych'),
('pl', 'common', 'empty', 'Pusto'),
('pl', 'common', 'actions', 'Akcje'),
('pl', 'common', 'options', 'Opcje'),
('pl', 'common', 'settings', 'Ustawienia'),
('pl', 'common', 'details', 'Szczegóły'),
('pl', 'common', 'info', 'Informacje'),
('pl', 'common', 'warning', 'Ostrzeżenie'),
('pl', 'common', 'danger', 'Niebezpieczeństwo'),
('pl', 'common', 'status', 'Status'),
('pl', 'common', 'active', 'Aktywny'),
('pl', 'common', 'inactive', 'Nieaktywny'),
('pl', 'common', 'enabled', 'Włączony'),
('pl', 'common', 'disabled', 'Wyłączony'),
('pl', 'common', 'visible', 'Widoczny'),
('pl', 'common', 'hidden', 'Ukryty'),
('pl', 'common', 'public', 'Publiczny'),
('pl', 'common', 'private', 'Prywatny'),
('pl', 'common', 'all', 'Wszystkie'),
('pl', 'common', 'none', 'Żaden'),
('pl', 'common', 'other', 'Inne'),
('pl', 'common', 'more', 'Więcej'),
('pl', 'common', 'less', 'Mniej'),
('pl', 'common', 'showMore', 'Pokaż więcej'),
('pl', 'common', 'showLess', 'Pokaż mniej'),
('pl', 'common', 'expandAll', 'Rozwiń wszystko'),
('pl', 'common', 'collapseAll', 'Zwiń wszystko'),
('pl', 'common', 'required', 'Wymagane'),
('pl', 'common', 'optional', 'Opcjonalne'),
('pl', 'common', 'date', 'Data'),
('pl', 'common', 'time', 'Czas'),
('pl', 'common', 'from', 'Od'),
('pl', 'common', 'to', 'Do'),
('pl', 'common', 'min', 'Min'),
('pl', 'common', 'max', 'Max')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();