INSERT INTO public.i18n_translations (language_code, namespace, key, value) VALUES
('pl','hk','pageTitle','Baza wiedzy'),
('pl','hk','subtitle','Materiały edukacyjne o zdrowiu i wellness'),
('pl','hk','testimonialsSubtitle','Opinie i efekty kuracji produktami Eqology'),
('pl','hk','tabMaterials','Materiały'),
('pl','hk','tabTestimonials','Prawdziwe Historie'),
('en','hk','pageTitle','Knowledge Base'),
('en','hk','subtitle','Educational materials on health and wellness'),
('en','hk','testimonialsSubtitle','Opinions and results from Eqology product treatments'),
('en','hk','tabMaterials','Materials'),
('en','hk','tabTestimonials','True Stories'),
('de','hk','pageTitle','Wissensdatenbank'),
('de','hk','subtitle','Bildungsmaterialien zu Gesundheit und Wellness'),
('de','hk','testimonialsSubtitle','Meinungen und Ergebnisse aus Eqology-Produktbehandlungen'),
('de','hk','tabMaterials','Materialien'),
('de','hk','tabTestimonials','Wahre Geschichten'),
('it','hk','pageTitle','Base di conoscenza'),
('it','hk','subtitle','Materiali educativi su salute e benessere'),
('it','hk','testimonialsSubtitle','Opinioni e risultati dei trattamenti con i prodotti Eqology'),
('it','hk','tabMaterials','Materiali'),
('it','hk','tabTestimonials','Storie vere'),
('es','hk','pageTitle','Base de conocimientos'),
('es','hk','subtitle','Materiales educativos sobre salud y bienestar'),
('es','hk','testimonialsSubtitle','Opiniones y resultados de los tratamientos con productos Eqology'),
('es','hk','tabMaterials','Materiales'),
('es','hk','tabTestimonials','Historias reales'),
('fr','hk','pageTitle','Base de connaissances'),
('fr','hk','subtitle','Matériel éducatif sur la santé et le bien-être'),
('fr','hk','testimonialsSubtitle','Avis et résultats des traitements avec les produits Eqology'),
('fr','hk','tabMaterials','Matériaux'),
('fr','hk','tabTestimonials','Histoires vraies'),
('pt','hk','pageTitle','Base de conhecimento'),
('pt','hk','subtitle','Materiais educacionais sobre saúde e bem-estar'),
('pt','hk','testimonialsSubtitle','Opiniões e resultados dos tratamentos com produtos Eqology'),
('pt','hk','tabMaterials','Materiais'),
('pt','hk','tabTestimonials','Histórias verdadeiras'),
('no','hk','pageTitle','Kunnskapsbase'),
('no','hk','subtitle','Pedagogisk materiale om helse og velvære'),
('no','hk','testimonialsSubtitle','Meninger og resultater fra Eqology-produktbehandlinger'),
('no','hk','tabMaterials','Materialer'),
('no','hk','tabTestimonials','Sanne historier')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();