-- Add translations for TrainingManagement and CertificateEditor components
INSERT INTO i18n_translations (language_code, namespace, key, value) VALUES
-- admin.training namespace
('pl', 'admin.training', 'title', 'Zarządzanie szkoleniami'),
('pl', 'admin.training', 'error', 'Błąd'),
('pl', 'admin.training', 'success', 'Sukces'),
('pl', 'admin.training', 'cannotLoadModules', 'Nie można załadować modułów szkoleniowych'),
('pl', 'admin.training', 'cannotLoadLessons', 'Nie można załadować lekcji'),
('pl', 'admin.training', 'moduleUpdated', 'Moduł został zaktualizowany'),
('pl', 'admin.training', 'moduleCreated', 'Moduł został utworzony'),
('pl', 'admin.training', 'cannotSaveModule', 'Nie można zapisać modułu'),
('pl', 'admin.training', 'lessonUpdated', 'Lekcja została zaktualizowana'),
('pl', 'admin.training', 'lessonCreated', 'Lekcja została utworzona'),
('pl', 'admin.training', 'cannotSaveLesson', 'Nie można zapisać lekcji'),
('pl', 'admin.training', 'confirmDeleteModule', 'Czy na pewno chcesz usunąć ten moduł? Wszystkie powiązane lekcje też zostaną usunięte.'),
('pl', 'admin.training', 'moduleDeleted', 'Moduł został usunięty'),
('pl', 'admin.training', 'cannotDeleteModule', 'Nie można usunąć modułu'),
('pl', 'admin.training', 'confirmDeleteLesson', 'Czy na pewno chcesz usunąć tę lekcję?'),
('pl', 'admin.training', 'lessonDeleted', 'Lekcja została usunięta'),
('pl', 'admin.training', 'cannotDeleteLesson', 'Nie można usunąć lekcji'),
('pl', 'admin.training', 'cannotLoadProgress', 'Nie można załadować postępów użytkowników'),
('pl', 'admin.training', 'regeneratingCertificate', 'Regenerowanie certyfikatu...'),
('pl', 'admin.training', 'generatingCertificateFor', 'Trwa generowanie certyfikatu dla'),
('pl', 'admin.training', 'certificateGeneratedFor', 'Certyfikat został wygenerowany dla'),
('pl', 'admin.training', 'certificateGenerationError', 'Błąd generowania certyfikatu'),
('pl', 'admin.training', 'certificateGenerationFailed', 'Nie udało się wygenerować certyfikatu'),
('pl', 'admin.training', 'certificateDownloadFailed', 'Nie udało się pobrać certyfikatu'),
('pl', 'admin.training', 'newModule', 'Nowy moduł'),
('pl', 'admin.training', 'modules', 'Moduły'),
('pl', 'admin.training', 'lessons', 'Lekcje'),
('pl', 'admin.training', 'userProgress', 'Postępy użytkowników'),
('pl', 'admin.training', 'editModule', 'Edytuj moduł'),
('pl', 'admin.training', 'active', 'Aktywny'),
('pl', 'admin.training', 'inactive', 'Nieaktywny'),
('pl', 'admin.training', 'preview', 'Podgląd'),
('pl', 'admin.training', 'send', 'Wyślij'),
('pl', 'admin.training', 'edit', 'Edytuj'),
('pl', 'admin.training', 'visibleTo', 'Widoczny dla'),
('pl', 'admin.training', 'selectModule', 'Wybierz moduł'),
('pl', 'admin.training', 'newLesson', 'Nowa lekcja'),
('pl', 'admin.training', 'editLesson', 'Edytuj lekcję'),
-- admin.certificates namespace
('pl', 'admin.certificates', 'error', 'Błąd'),
('pl', 'admin.certificates', 'success', 'Sukces'),
('pl', 'admin.certificates', 'cannotLoadTemplates', 'Nie można załadować szablonów certyfikatów'),
('pl', 'admin.certificates', 'templateNameRequired', 'Nazwa szablonu jest wymagana'),
('pl', 'admin.certificates', 'templateCreated', 'Szablon certyfikatu został utworzony'),
('pl', 'admin.certificates', 'templateCreationFailed', 'Nie udało się utworzyć szablonu')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value;