-- Add translations for MaintenanceModeManagement and DailySignalManagement components
INSERT INTO i18n_translations (language_code, namespace, key, value) VALUES
-- admin.maintenance namespace
('pl', 'admin.maintenance', 'title', 'Tryb serwisowy'),
('pl', 'admin.maintenance', 'defaultTitle', 'Przerwa techniczna'),
('pl', 'admin.maintenance', 'defaultMessage', 'Trwają prace serwisowe. Prosimy o cierpliwość.'),
('pl', 'admin.maintenance', 'fetchError', 'Błąd podczas pobierania ustawień serwisowych'),
('pl', 'admin.maintenance', 'enabledSuccess', 'Tryb serwisowy włączony - strona logowania jest zablokowana'),
('pl', 'admin.maintenance', 'savedSuccess', 'Ustawienia zapisane'),
('pl', 'admin.maintenance', 'saveError', 'Błąd podczas zapisywania ustawień'),
('pl', 'admin.maintenance', 'bypassEmailSent', 'Email z linkiem bypass wysłany na'),
('pl', 'admin.maintenance', 'bypassEmailError', 'Błąd podczas wysyłania emaila'),
('pl', 'admin.maintenance', 'bypassKeyGenerated', 'Wygenerowano nowy klucz bypass'),
('pl', 'admin.maintenance', 'bypassKeyError', 'Błąd podczas generowania klucza'),
('pl', 'admin.maintenance', 'linkCopied', 'Link skopiowany do schowka'),
('pl', 'admin.maintenance', 'modeEnabled', '🔧 Tryb serwisowy WŁĄCZONY - logowanie zablokowane'),
('pl', 'admin.maintenance', 'modeDisabled', '✅ Tryb serwisowy WYŁĄCZONY - logowanie dostępne'),
('pl', 'admin.maintenance', 'toggleError', 'Błąd podczas zmiany trybu'),
('pl', 'admin.maintenance', 'loading', 'Ładowanie ustawień...'),
('pl', 'admin.maintenance', 'statusBlocked', 'Strona logowania i rejestracji jest zablokowana'),
('pl', 'admin.maintenance', 'statusNormal', 'Użytkownicy mogą się normalnie logować i rejestrować'),
('pl', 'admin.maintenance', 'active', 'AKTYWNY'),
('pl', 'admin.maintenance', 'inactive', 'Wyłączony'),
('pl', 'admin.maintenance', 'bypassLinkTitle', 'Link dostępu administratora'),
('pl', 'admin.maintenance', 'bypassLinkDescription', 'Użyj tego linku, aby zalogować się podczas prac serwisowych:'),
('pl', 'admin.maintenance', 'sending', 'Wysyłanie...'),
('pl', 'admin.maintenance', 'sendToEmail', 'Wyślij na email'),
('pl', 'admin.maintenance', 'newKey', 'Nowy klucz'),
('pl', 'admin.maintenance', 'emailSentAutomatically', 'Email z linkiem został automatycznie wysłany przy aktywacji trybu serwisowego'),
('pl', 'admin.maintenance', 'bannerConfigTitle', 'Konfiguracja banera'),
('pl', 'admin.maintenance', 'bannerConfigDescription', 'Ustaw treść i czas zakończenia prac serwisowych'),
('pl', 'admin.maintenance', 'bannerTitleLabel', 'Tytuł banera'),
('pl', 'admin.maintenance', 'messageLabel', 'Treść komunikatu'),
('pl', 'admin.maintenance', 'plannedEndLabel', 'Planowany czas zakończenia prac'),
('pl', 'admin.maintenance', 'plannedEndHint', 'Pozostaw puste, jeśli czas zakończenia jest nieznany'),
('pl', 'admin.maintenance', 'saving', 'Zapisywanie...'),
('pl', 'admin.maintenance', 'saveSettings', 'Zapisz ustawienia'),
('pl', 'admin.maintenance', 'preview', 'Podgląd'),
('pl', 'admin.maintenance', 'warningTitle', 'Uwaga!'),
('pl', 'admin.maintenance', 'warningDescription', 'Tryb serwisowy jest aktywny. Użytkownicy nie mogą się logować ani rejestrować. Pamiętaj, aby wyłączyć tryb serwisowy po zakończeniu prac.'),
('pl', 'admin.maintenance', 'enableWarningTitle', 'Włączenie trybu serwisowego'),
('pl', 'admin.maintenance', 'enableWarningDescription', 'Włączenie trybu serwisowego zablokuje dostęp do logowania i rejestracji dla wszystkich użytkowników.'),
('pl', 'admin.maintenance', 'enableWarningEmail', 'Po zatwierdzeniu automatycznie otrzymasz email z linkiem umożliwiającym logowanie'),
('pl', 'admin.maintenance', 'confirmQuestion', 'Czy na pewno chcesz kontynuować?'),
('pl', 'admin.maintenance', 'confirmEnable', 'Tak, włącz tryb serwisowy'),
('pl', 'admin.maintenance', 'closePreview', 'Zamknij podgląd'),
-- admin.dailySignal namespace
('pl', 'admin.dailySignal', 'fetchError', 'Nie udało się pobrać danych'),
('pl', 'admin.dailySignal', 'settingsUpdated', 'Ustawienia zostały zaktualizowane'),
('pl', 'admin.dailySignal', 'settingsUpdateError', 'Nie udało się zapisać ustawień'),
('pl', 'admin.dailySignal', 'aiFunctionError', 'Błąd funkcji AI'),
('pl', 'admin.dailySignal', 'aiNoData', 'AI nie zwróciło poprawnych danych'),
('pl', 'admin.dailySignal', 'generatedCount', 'Wygenerowano {count} sygnałów'),
('pl', 'admin.dailySignal', 'autoApproved', 'Sygnały zostały automatycznie zatwierdzone'),
('pl', 'admin.dailySignal', 'pendingApproval', 'Sygnały czekają na zatwierdzenie'),
('pl', 'admin.dailySignal', 'generationError', 'Błąd generowania'),
('pl', 'admin.dailySignal', 'generationFailed', 'Nie udało się wygenerować sygnałów'),
('pl', 'admin.dailySignal', 'activated', 'Aktywowano'),
('pl', 'admin.dailySignal', 'deactivated', 'Dezaktywowano'),
('pl', 'admin.dailySignal', 'activatedDescription', 'Sygnał jest teraz dostępny w rotacji'),
('pl', 'admin.dailySignal', 'deactivatedDescription', 'Sygnał został wyłączony z rotacji'),
('pl', 'admin.dailySignal', 'statusChangeError', 'Nie udało się zmienić statusu'),
('pl', 'admin.dailySignal', 'deleteConfirm', 'Czy na pewno chcesz usunąć ten sygnał?'),
('pl', 'admin.dailySignal', 'deleted', 'Sygnał został usunięty'),
('pl', 'admin.dailySignal', 'deleteError', 'Nie udało się usunąć sygnału'),
('pl', 'admin.dailySignal', 'fillRequiredFields', 'Wypełnij wszystkie wymagane pola'),
('pl', 'admin.dailySignal', 'added', 'Nowy sygnał został dodany do biblioteki'),
('pl', 'admin.dailySignal', 'saveError', 'Nie udało się zapisać sygnału'),
('pl', 'admin.dailySignal', 'updated', 'Sygnał został zaktualizowany'),
('pl', 'admin.dailySignal', 'updateError', 'Nie udało się zaktualizować sygnału'),
-- toast common keys
('pl', 'toast', 'deleted', 'Usunięto'),
('pl', 'toast', 'added', 'Dodano'),
-- common namespace
('pl', 'common', 'cancel', 'Anuluj')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value;