-- Insert translation keys for DailySignalManagement
INSERT INTO i18n_translations (language_code, namespace, key, value) VALUES
-- UI Elements
('pl', 'admin.dailySignal', 'tabs.settings', 'Ustawienia'),
('pl', 'admin.dailySignal', 'tabs.library', 'Biblioteka'),
('pl', 'admin.dailySignal', 'tabs.statistics', 'Statystyki'),
('pl', 'admin.dailySignal', 'globalSettings', 'Ustawienia globalne'),
('pl', 'admin.dailySignal', 'globalSettingsDescription', 'Kontroluj wyświetlanie i generowanie Sygnału Dnia'),
('pl', 'admin.dailySignal', 'enableSignal', 'Włącz Sygnał Dnia'),
('pl', 'admin.dailySignal', 'globallyEnables', 'Globalnie włącza lub wyłącza funkcję'),
('pl', 'admin.dailySignal', 'displayFrequency', 'Częstotliwość wyświetlania'),
('pl', 'admin.dailySignal', 'displayFrequencyHint', 'Jak często użytkownicy widzą Sygnał Dnia'),
('pl', 'admin.dailySignal', 'onceDaily', 'Raz dziennie'),
('pl', 'admin.dailySignal', 'everyLogin', 'Przy każdym logowaniu'),
('pl', 'admin.dailySignal', 'roleVisibility', 'Widoczność dla ról'),
('pl', 'admin.dailySignal', 'clients', 'Klienci'),
('pl', 'admin.dailySignal', 'partners', 'Partnerzy'),
('pl', 'admin.dailySignal', 'specialists', 'Specjaliści'),
('pl', 'admin.dailySignal', 'generationMode', 'Tryb generowania'),
('pl', 'admin.dailySignal', 'autoMode', 'Automatyczny (AI bez akceptacji)'),
('pl', 'admin.dailySignal', 'semiAutoMode', 'Półautomatyczny (AI + akceptacja)'),
('pl', 'admin.dailySignal', 'manualMode', 'Manualny (tylko ręczne wpisy)'),
('pl', 'admin.dailySignal', 'animationType', 'Animacja pojawiania się'),
('pl', 'admin.dailySignal', 'noAnimation', 'Brak animacji'),
('pl', 'admin.dailySignal', 'fadeIn', 'Fade In'),
('pl', 'admin.dailySignal', 'slideUp', 'Slide Up'),
('pl', 'admin.dailySignal', 'slideDown', 'Slide Down'),
('pl', 'admin.dailySignal', 'scaleIn', 'Scale In (Zoom)'),
('pl', 'admin.dailySignal', 'animationIntensity', 'Intensywność animacji'),
('pl', 'admin.dailySignal', 'off', 'Wyłączona'),
('pl', 'admin.dailySignal', 'subtle', 'Subtelna (domyślna)'),
('pl', 'admin.dailySignal', 'enhanced', 'Wzmocniona'),
('pl', 'admin.dailySignal', 'addOwn', 'Dodaj własny'),
('pl', 'admin.dailySignal', 'generating', 'Generowanie...'),
('pl', 'admin.dailySignal', 'generateWithAI', 'Generuj z AI'),
('pl', 'admin.dailySignal', 'allTypes', 'Wszystkie typy'),
('pl', 'admin.dailySignal', 'supportive', 'Wspierający'),
('pl', 'admin.dailySignal', 'motivational', 'Motywacyjny'),
('pl', 'admin.dailySignal', 'calm', 'Spokojny'),
('pl', 'admin.dailySignal', 'allSources', 'Wszystkie źródła'),
('pl', 'admin.dailySignal', 'allStatuses', 'Wszystkie statusy'),
('pl', 'admin.dailySignal', 'activeStatus', 'Aktywne'),
('pl', 'admin.dailySignal', 'inactiveStatus', 'Nieaktywne'),
('pl', 'admin.dailySignal', 'signalsCount', 'z {total} sygnałów'),
('pl', 'admin.dailySignal', 'noSignals', 'Brak sygnałów. Dodaj pierwszy sygnał ręcznie lub wygeneruj z AI.'),
('pl', 'admin.dailySignal', 'noMatchingSignals', 'Brak sygnałów pasujących do filtrów.'),
('pl', 'admin.dailySignal', 'used', 'Wykorzystany'),
('pl', 'admin.dailySignal', 'detailedStats', 'Szczegółowe statystyki'),
('pl', 'admin.dailySignal', 'usedSignalsCount', 'Wykorzystane sygnały'),
('pl', 'admin.dailySignal', 'availableToDisplay', 'Dostępne do wyświetlenia (aktywne)'),
('pl', 'admin.dailySignal', 'supportiveSignals', 'Sygnały wspierające'),
('pl', 'admin.dailySignal', 'motivationalSignals', 'Sygnały motywacyjne'),
('pl', 'admin.dailySignal', 'calmSignals', 'Sygnały spokojne'),
('pl', 'admin.dailySignal', 'usersWithPrefs', 'Użytkownicy z zapisanymi preferencjami'),
('pl', 'admin.dailySignal', 'generateTitle', 'Generuj sygnały z AI'),
('pl', 'admin.dailySignal', 'generateDescription', 'Wybierz liczbę sygnałów i ton generowania'),
('pl', 'admin.dailySignal', 'signalCount', 'Ilość sygnałów'),
('pl', 'admin.dailySignal', 'signalTone', 'Ton sygnałów'),
('pl', 'admin.dailySignal', 'generateCount', 'Generuj {count} sygnałów'),
('pl', 'admin.dailySignal', 'addOwnSignal', 'Dodaj własny sygnał'),
('pl', 'admin.dailySignal', 'addOwnDescription', 'Stwórz własny Sygnał Dnia (źródło: admin)'),
('pl', 'admin.dailySignal', 'signalType', 'Typ sygnału'),
('pl', 'admin.dailySignal', 'mainContent', 'Główna treść'),
('pl', 'admin.dailySignal', 'mainContentPlaceholder', 'Wpisz główne przesłanie (max 15 słów)...'),
('pl', 'admin.dailySignal', 'whyThisSignal', 'Dlaczego dziś ten sygnał?'),
('pl', 'admin.dailySignal', 'explanationPlaceholder', 'Wpisz wyjaśnienie (max 20 słów)...'),
('pl', 'admin.dailySignal', 'displayDate', 'Data wyświetlenia (opcjonalne)'),
('pl', 'admin.dailySignal', 'addSignal', 'Dodaj sygnał'),
('pl', 'admin.dailySignal', 'editSignal', 'Edytuj sygnał'),
('pl', 'admin.dailySignal', 'saveChanges', 'Zapisz zmiany'),
('pl', 'admin.dailySignal', 'all', 'Wszystkie'),
('pl', 'admin.dailySignal', 'source', 'Źródło'),
('pl', 'admin.dailySignal', 'signalTypes', 'Typy sygnałów'),
('pl', 'admin.dailySignal', 'users', 'Użytkownicy'),
('pl', 'admin.dailySignal', 'enabled', 'Włączone'),
('pl', 'admin.dailySignal', 'disabled', 'Wyłączone'),

-- ImportantInfoManagement translations
('pl', 'admin.importantInfo', 'banners', 'Banery informacyjne'),
('pl', 'admin.importantInfo', 'stats', 'Statystyki'),
('pl', 'admin.importantInfo', 'manageBanners', 'Zarządzanie banerami'),
('pl', 'admin.importantInfo', 'addBanner', 'Dodaj baner'),
('pl', 'admin.importantInfo', 'editBanner', 'Edytuj baner'),
('pl', 'admin.importantInfo', 'newBanner', 'Nowy baner informacyjny'),
('pl', 'admin.importantInfo', 'title', 'Tytuł'),
('pl', 'admin.importantInfo', 'styling', 'Stylizacja'),
('pl', 'admin.importantInfo', 'content', 'Treść komunikatu (edytor tekstowy)'),
('pl', 'admin.importantInfo', 'image', 'Obrazek (opcjonalnie)'),
('pl', 'admin.importantInfo', 'bold', 'Pogrubiony'),
('pl', 'admin.importantInfo', 'largeSize', 'Duży rozmiar'),
('pl', 'admin.importantInfo', 'underline', 'Podkreślenie'),
('pl', 'admin.importantInfo', 'shadow', 'Cień'),
('pl', 'admin.importantInfo', 'accentColor', 'Kolor akcentu'),
('pl', 'admin.importantInfo', 'customColor', 'Własny kolor tytułu'),
('pl', 'admin.importantInfo', 'reset', 'Resetuj'),
('pl', 'admin.importantInfo', 'button', 'Przycisk w banerze'),
('pl', 'admin.importantInfo', 'buttonText', 'Tekst przycisku'),
('pl', 'admin.importantInfo', 'buttonUrl', 'URL przycisku'),
('pl', 'admin.importantInfo', 'buttonColor', 'Kolor przycisku'),
('pl', 'admin.importantInfo', 'buttonIcon', 'Ikona przycisku'),
('pl', 'admin.importantInfo', 'scheduledDate', 'Data startu (opcjonalne)'),
('pl', 'admin.importantInfo', 'expirationDate', 'Data wygaśnięcia (opcjonalne)'),
('pl', 'admin.importantInfo', 'displayFrequency', 'Częstotliwość wyświetlania'),
('pl', 'admin.importantInfo', 'once', 'Raz (do zamknięcia)'),
('pl', 'admin.importantInfo', 'daily', 'Raz dziennie'),
('pl', 'admin.importantInfo', 'always', 'Zawsze'),
('pl', 'admin.importantInfo', 'priority', 'Priorytet'),
('pl', 'admin.importantInfo', 'roleVisibility', 'Widoczność dla ról'),
('pl', 'admin.importantInfo', 'animation', 'Animacja'),
('pl', 'admin.importantInfo', 'noAnimation', 'Brak animacji'),
('pl', 'admin.importantInfo', 'animationIntensity', 'Intensywność animacji'),
('pl', 'admin.importantInfo', 'save', 'Zapisz'),
('pl', 'admin.importantInfo', 'cancel', 'Anuluj'),
('pl', 'admin.importantInfo', 'noBanners', 'Brak banerów. Utwórz pierwszy!'),
('pl', 'admin.importantInfo', 'active', 'Aktywny'),
('pl', 'admin.importantInfo', 'scheduled', 'Zaplanowany'),
('pl', 'admin.importantInfo', 'expired', 'Wygasł'),
('pl', 'admin.importantInfo', 'loading', 'Ładowanie...'),
('pl', 'admin.importantInfo', 'fetchError', 'Błąd podczas pobierania danych'),
('pl', 'admin.importantInfo', 'saveSuccess', 'Baner zaktualizowany'),
('pl', 'admin.importantInfo', 'createSuccess', 'Baner utworzony'),
('pl', 'admin.importantInfo', 'saveError', 'Błąd podczas zapisywania'),
('pl', 'admin.importantInfo', 'deleteConfirm', 'Czy na pewno chcesz usunąć ten baner?'),
('pl', 'admin.importantInfo', 'deleteSuccess', 'Baner usunięty'),
('pl', 'admin.importantInfo', 'deleteError', 'Błąd podczas usuwania'),
('pl', 'admin.importantInfo', 'toggleSuccess', 'Status banera zmieniony'),
('pl', 'admin.importantInfo', 'toggleError', 'Błąd podczas zmiany statusu'),
('pl', 'admin.importantInfo', 'contentRequired', 'Treść banera jest wymagana'),
('pl', 'admin.importantInfo', 'totalBanners', 'Wszystkie banery'),
('pl', 'admin.importantInfo', 'activeBanners', 'Aktywne banery'),
('pl', 'admin.importantInfo', 'totalDismissals', 'Zamknięcia banerów'),

-- CookieConsentManagement translations
('pl', 'admin.cookies', 'title', 'Zarządzanie Cookies'),
('pl', 'admin.cookies', 'hidePreview', 'Ukryj podgląd'),
('pl', 'admin.cookies', 'preview', 'Podgląd'),
('pl', 'admin.cookies', 'saving', 'Zapisywanie...'),
('pl', 'admin.cookies', 'saveSettings', 'Zapisz ustawienia'),
('pl', 'admin.cookies', 'tabs.general', 'Ogólne'),
('pl', 'admin.cookies', 'tabs.layout', 'Układ'),
('pl', 'admin.cookies', 'tabs.content', 'Treść'),
('pl', 'admin.cookies', 'tabs.colors', 'Kolory'),
('pl', 'admin.cookies', 'tabs.categories', 'Kategorie'),
('pl', 'admin.cookies', 'tabs.stats', 'Statystyki'),
('pl', 'admin.cookies', 'generalSettings', 'Ustawienia ogólne'),
('pl', 'admin.cookies', 'generalDescription', 'Podstawowe ustawienia modułu cookie consent'),
('pl', 'admin.cookies', 'enableModule', 'Włącz moduł Cookie Consent'),
('pl', 'admin.cookies', 'bannerWillShow', 'Banner będzie wyświetlany użytkownikom'),
('pl', 'admin.cookies', 'consentTemplate', 'Szablon zgody'),
('pl', 'admin.cookies', 'expirationDays', 'Czas wygaśnięcia zgody (dni)'),
('pl', 'admin.cookies', 'reloadOnConsent', 'Przeładuj stronę po zgodzie'),
('pl', 'admin.cookies', 'refreshesPage', 'Odświeża stronę po zapisaniu preferencji'),
('pl', 'admin.cookies', 'geoTargeting', 'Geo-targeting'),
('pl', 'admin.cookies', 'showInCountries', 'Wyświetlaj tylko w wybranych krajach'),
('pl', 'admin.cookies', 'layoutSettings', 'Układ bannera'),
('pl', 'admin.cookies', 'layoutDescription', 'Wybierz typ i pozycję bannera'),
('pl', 'admin.cookies', 'bannerType', 'Typ bannera'),
('pl', 'admin.cookies', 'position', 'Pozycja'),
('pl', 'admin.cookies', 'preferenceCenterType', 'Typ Preference Center'),
('pl', 'admin.cookies', 'closeButton', 'Przycisk zamknięcia'),
('pl', 'admin.cookies', 'showCloseButton', 'Pokaż przycisk X'),
('pl', 'admin.cookies', 'categoriesFirstLayer', 'Kategorie na pierwszej warstwie'),
('pl', 'admin.cookies', 'showCheckboxes', 'Pokaż checkboxy kategorii od razu'),
('pl', 'admin.cookies', 'revisitButton', 'Przycisk powrotu (Revisit)'),
('pl', 'admin.cookies', 'floatingButton', 'Pływający przycisk po udzieleniu zgody'),
('pl', 'admin.cookies', 'revisitPosition', 'Pozycja przycisku Revisit'),
('pl', 'admin.cookies', 'contentSettings', 'Treść bannera'),
('pl', 'admin.cookies', 'contentDescription', 'Edytuj teksty i przyciski'),
('pl', 'admin.cookies', 'bannerTitle', 'Tytuł'),
('pl', 'admin.cookies', 'message', 'Wiadomość'),
('pl', 'admin.cookies', 'privacyPolicyUrl', 'URL Polityki Prywatności'),
('pl', 'admin.cookies', 'customLogoUrl', 'URL własnego logo'),

-- Common translations
('pl', 'common', 'loading', 'Ładowanie...'),
('pl', 'common', 'save', 'Zapisz'),
('pl', 'common', 'add', 'Dodaj'),
('pl', 'common', 'edit', 'Edytuj'),
('pl', 'common', 'inactive', 'Nieaktywny'),
('pl', 'common', 'client', 'Klient'),
('pl', 'common', 'all', 'Wszystkie'),

-- Toast translations
('pl', 'toast', 'deleted', 'Usunięto'),
('pl', 'toast', 'added', 'Dodano'),
('pl', 'toast', 'saved', 'Zapisano')
ON CONFLICT (language_code, namespace, key) DO UPDATE SET value = EXCLUDED.value;